### ISSUE TITLE
survSplit() does not return start variable name for interval Surv() object in 2.40-1

### ISSUE THREAD

**Issue by jeffeaton** [therneau/survival#10]
Hello, I just updated to survival_2.40-1, and the survSplit() function no longer seems to return the variable name of the interval start time if specifying an interval Surv() object. Example below (variable name 't0' renamed to 'tstart'):

> data(veteran)
> veteran$t0 <- runif(nrow(veteran), 0, veteran$time)
> vet2 <- survSplit(Surv(t0, time, status) ~., veteran, cut=c(60, 120), episode ="timegroup")
> head(vet2)
  trt celltype karno diagtime age prior    tstart time status timegroup
1   1 squamous    60        7  69     0  35.90687   60      0         1
2   1 squamous    60        7  69     0  60.00000   72      1         2
3   1 squamous    70        5  64    10  28.55607   60      0         1
4   1 squamous    70        5  64    10  60.00000  120      0         2
5   1 squamous    70        5  64    10 120.00000  411      1         3
6   1 squamous    60        3  38     0  49.76141   60      0         1

It seemed to work fine in version 2.39-5:

> data(veteran)
> veteran$t0 <- runif(nrow(veteran), 0, veteran$time)
> vet2 <- survSplit(Surv(t0, time, status) ~., veteran, cut=c(60, 120), episode ="timegroup")
> head(vet2)
  trt celltype karno diagtime age prior         t0 time status timegroup
1   1 squamous    60        7  69     0   8.278983   60      0         1
2   1 squamous    60        7  69     0  60.000000   72      1         2
3   1 squamous    70        5  64    10 403.371329  411      1         3
4   1 squamous    60        3  38     0  58.903782   60      0         1
5   1 squamous    60        3  38     0  60.000000  120      0         2
6   1 squamous    60        3  38     0 120.000000  228      1         3

**Comment by therneau** [comment]
THat is not a change that I intended.  I'll look into it --- but not for a couple weeks as 
I'm about to go out of town.

Terry T.

**Comment by therneau** [comment]
fixed in 2.41
