### ISSUE TITLE
Concordance.R returns 'x and y are not the same length' when using newdata option for a survreg model

### ISSUE THREAD

**Issue by ajaidas** [therneau/survival#101]
I get the following error when I try to use concordance with newdata:

"Error in (function (y, x, strata, weights, ymin = NULL, ymax = NULL, timewt = c("n",  : 
  x and y are not the same length"

I see there is an earlier closed issue mentioning a cox model. However, I am still getting the error.

**Comment by therneau** [comment]
Fixed
