### ISSUE TITLE
Clogit - questions - error 

### ISSUE THREAD

**Issue by JeremyTournayre** [therneau/survival#104]
Hello,

I'm using your clogit function with a dataset. I have three questions :

1) I try several combinations of variables and sometimes I get results with NA:
https://ibb.co/0sT334S
 
The function does not return warnings.

Can you help me please?

2) With certain combinations of variables the function gives me a warnings, even an error:

An error : 
 https://ibb.co/cD23NrX
In english : Error in fitter (X, Y, istrat, offset, init, control, weights = weights, : NA/NaN/Inf in foreign function call (arg 5)

A warning : 
 https://ibb.co/0rYkzQW

I imagine I put too many variables, is that right?
If there is a warning, the results can still be used?

3) I have a last question :

With another combination of oxylipines I get very high coefficient values unlike usual, is it normal?
 
https://ibb.co/qDn8yx3

With another combination, I don't have extreme values : 
 
https://ibb.co/6nX4Ft1

Yours faithfully,
Jérémy Tournayre

**Comment by therneau** [comment]
Without data I can only comment in general, but my guess is that you have too many variables and too few events, leading to infinite hazard ratios.  The coxph function does not always do well with infinity.  (I keep making it better, but it requires reproducable examples.)
