### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by jotheeswaranAT** [therneau/survival#105]
Hi, 

I am having great difficulty in installing this package . 

> library(survival)
Error in value[[3L]](cond) : 
  Package ‘survival’ version 3.1.12 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘survival’ is imported by ‘Hmisc’, ‘DynNom’, ‘multcomp’, ‘TH.data’, ‘rms’ so cannot be unloaded

I tried to install directly from GitHub, but I do have problem. 

> library(devtools) 
> install_git("therneau/survival") 
Error: Failed to install 'unknown package' from Git:
  Error in 'git2r_remote_ls': unsupported URL protocol

Could you please advise me? I need to conduct the survival analysis urgently. 

Regards, 

JOTHEES

**Comment by therneau** [comment]
I don't know what version of R you have, try sessionInfo().  I suspect it should be updated first.

**Comment by jotheeswaranAT** [comment]
Hi,

Thank you for email.

I am using latest R studio package.

I am able to run other command from the survminer and survival packages, but just not ggcoxadjusted curve. I am missing something?

> ggadjustedcurves(res.cox, data=survival_olderadult,individual.curves =TRUE)
> ggcoxadjustedcurves(res.cox, data=survival_olderadult,individual.curves =TRUE)
Error in ggcoxadjustedcurves(res.cox, data = survival_olderadult, individual.curves = TRUE) :
  could not find function "ggcoxadjustedcurves"


Regards,

Dr Jotheeswaran  A Thiyagarajan
Technical Officer (Epidemiologist)
Department of Maternal, Newborn, Child, Adolescent Health and Ageing

[cid:image003.png@01D4CDB1.4C05A1D0]

20, AVENUE APPIA
CH-1211 GENEVA 27

Tel. direct: +41 22 791 1248
Fax direct: +41 22 791 1585
Office Room: 5022 5th Floor
Mobile no: +41 768019143
 Email ID : amuthavallithiya@who.int<mailto:amuthavallithiya@who.int>
