### ISSUE TITLE
Include model.frame in results objects

### ISSUE THREAD

**Issue by jrdnmdhl** [therneau/survival#11]
I am currently working on S3 generics for a package which will need a method for survfit objects.  However, I have run into some trouble because it doesn't seem reliably possible to recreate the model.frame from a survfit object since it contains neither the full data, nor the model.frame.

There is precedent in other packages for including this in the returned object.  As an example, lm includes the resulting model.frame in the model property of the lm object.

**Comment by therneau** [comment]
There is also precedent for not including it in the result, e.g., every other function in 
the survival package.  Yes, lm does this, but I do not consider it good design in general.

Can you be more specific about what you need to do?

Terry T.

**Comment by jrdnmdhl** [comment]
I am trying to essentially write a predict method for survfit (and other survival-related objects), but one that returns the results in a tidy data.frame with the same column names for the predictors as used in the original data.  It can either do this for a user-supplied data.frame of covariates/indicators or will use the original data by default.

Having spent a few more hours on it, I believe can probably accomplish this with string processing the names of the strata vector.  That is not my preferred solution, but I'm not sure that it is worth making any changes, particularly if you don't like the concept.

Thank you for your time!

**Comment by therneau** [comment]
Remember that survfit is a method: multiple routines create these objects. You won't 
always be able to depend on the form of the strata argument.  This is part of what makes 
it not obvious to me how I would add a model.frame component to the result.  The 
survfit.coxph and survfit.ms objects inherit from survfit, so you can distinguish the 
source, however.

Terry T.

**Comment by jrdnmdhl** [comment]
Perhaps my best solution is to simply wrap the relevant methods from survival?  The information I need to map covariate levels to strata isn't necessarily going to exist in the survfit object, but a wrapper can fix that by preserving anything necessary from the original call.

**Comment by therneau** [comment]
I have a grant due on Wed afternoon, and simply cant follow up until that is done.  I may 
have an error in the github archive. That's my "working" copy, and I do full checks when I 
submit to CRAN.  (Full checks eat up 1-3 days, so I can't always do them.)

**Comment by therneau** [comment]
"I am trying to essentially write a predict method for survfit (and other survival-related objects), but one that returns the results in a tidy data.frame with the same column names for the predictors as used in the original data. It can either do this for a user-supplied data.frame of covariates/indicators or will use the original data by default."
That is not something that I would find worthwhile.  But there is a part within it that I will have to think about, which would be to have the strata component of a survival curve be a data frame with the variable name as columns (as you say) and another variable named "(nrow)" or some such, with one row per curve.  Your object would be the merge of this with the curves themselves.   But changing survival curves is tough --- lots and lots of packages know how to use and manipulate them....
