### ISSUE TITLE
Very extremes coefficients  (10^-15 to 10^7)

### ISSUE THREAD

**Issue by JeremyTournayre** [therneau/survival#110]
Hello,

Thank you for your answer to my issue : https://github.com/therneau/survival/issues/104.

I would like more information about the very extremes coefficients values that I obtain please.

The data is in the archive at the address : http://dl.free.fr/ldHRbufni

In the archive there is the file "data.Rdata" containing the data and the file "odd_ratio_clogit.r" containing only the command lines:

library(survival)
load("data.Rdata")
clogit(data[,1] ~ data[,2] + data[,3] + data[,4] + data[,5] + data[,6] + data[,7] + data[,8] + data[,9] +data[,10] + data[,11] + data[,12] + strata(data[,13]), data = data)

This gives the following coefficients : 

-----exp(coef)
data[, 2]           5.78E-15
data[, 3]            4.82E+07
data[, 4]           4.49E-08
data[, 5]           1.82E-06
data[, 6]           1.86E+04
data[, 7]           1.18E+07
data[, 8]           2.64E-05
data[, 9]            1.20E+04
data[, 10]          3.85E-04
data[, 11]urban      2.61E+02
data[, 12]secondary 8.84E-15
data[, 12]superior    4.11E-17

I wonder if it's normal to have such extremes coefficients?

Yours faithfully,
Jérémy Tournayre

**Comment by therneau** [comment]
I didn't get to this for a month, and the data file/web address you reference is not available.  
A rule of thumb for stable Cox model regression is 10-20 events per covariate.   My first check would have been to count your events.  For clogit, any strata with the event after the censor do not add information so do not count in the total.
