### ISSUE TITLE
Partial match in `model.matrix`

### ISSUE THREAD

**Issue by FCACollin** [therneau/survival#112]
I would kindly suggest the correction of a partial argument match.

```r
model.matrix.default(Terms, mf, contrasts = contrast.arg): partial argument match of 'contrasts' to 'contrasts.arg'
```

Modifications should be effective at locations:

https://github.com/therneau/survival/blob/67f4a4036b03d493de6384dedf9967c6ab079644/R/model.matrix.coxph.R#L48

https://github.com/therneau/survival/blob/3d67547efa9373b6668c20f758de8b2c98d991ca/R/coxph.R#L426

https://github.com/therneau/survival/blob/3d67547efa9373b6668c20f758de8b2c98d991ca/noweb/coxph.Rnw#L921

The alternative would be:

```r
X <- model.matrix(Terms2, mf,  contrasts.arg=contrast.arg)
```

in replacement of:

```r
 X <- model.matrix(Terms2, mf, constrasts=contrast.arg) 
```

**Comment by therneau** [comment]
Good catch.  Now fixed in my master copy.  (Github is a delayed mirror of it.)
