### ISSUE TITLE
linearHypothesis.survreg() not omitting Log(scale) and producing non-conformable argument with Weibull survival regression

### ISSUE THREAD

**Issue by rdinter** [therneau/survival#113]
Apologies if this is not the correct repository for this issue, but constructing a linear restriction of coefficients on a Weibull survival regression produces a non-conformable arguments which I believe is due to the `Log(scale)` term in the variance-covariance matrix not being correctly removed. To demonstrate with the generic example from `survreg()` documentation:

``` r
library(survival)
library(car)
#> Loading required package: carData

reg1 <- survreg(Surv(futime, fustat) ~ ecog.ps + rx, ovarian, dist='weibull')
linearHypothesis(reg1, "ecog.ps = rx")
#> Error in L %*% V: non-conformable arguments
linearHypothesis(reg1, "ecog.ps = rx", vcov. = vcov(reg1)[-4,-4])
#> Linear hypothesis test
#> 
#> Hypothesis:
#> ecog.ps - rx = 0
#> 
#> Model 1: restricted model
#> Model 2: Surv(futime, fustat) ~ ecog.ps + rx
#> 
#> Note: Coefficient covariance matrix supplied.
#> 
#>   Res.Df Df  Chisq Pr(>Chisq)
#> 1     23                     
#> 2     22  1 1.5584     0.2119

reg2 <- survreg(Surv(futime, fustat) ~ ecog.ps + rx, ovarian, dist="exponential")
linearHypothesis(reg2, "ecog.ps = rx")
#> Linear hypothesis test
#> 
#> Hypothesis:
#> ecog.ps - rx = 0
#> 
#> Model 1: restricted model
#> Model 2: Surv(futime, fustat) ~ ecog.ps + rx
#> 
#>   Res.Df Df  Chisq Pr(>Chisq)
#> 1     24                     
#> 2     23  1 1.6069     0.2049
```

Manually omitting the `Log(scale)` row/column from the variance covariance matrix will produce the expected result, however the non-conformable argument appears under the defaulted variance covariance matrix.

**Comment by therneau** [comment]
This turns out to be a statistical question, and the discussion was moved to email.
