### ISSUE TITLE
Mislabeled legend at `help(mugs1)`

### ISSUE THREAD

**Issue by jbhender** [therneau/survival#115]
The legend at `help(mugs1)` currently mislabels groups and cumulative incidence curves.

Here's the plotting statement:
```
plot(sfit, xscale=365.25, lty=c(2,1,2,1), col=c(1,1,2,2),
     xlab="Years after MGUS detection", ylab="Proportion")
```

And here's the order from `print(sfit)`:

Call: survfit(formula = Surv(start, stop, event) ~ sex, data = mgus1, 
    subset = (enum == 1), id = id)

                    n nevent   rmean*
sex=female, (s0)  104      0 5762.379
sex=male, (s0)    137      0 4543.293
sex=female, pcm   104     33 2881.500
sex=male, pcm     137     31 2478.026
sex=female, death 104     63 5681.121
sex=male, death   137    100 7303.682
   *mean time in state, restricted (max time = 14325 )

Current legend:
legend(0, .8, c("Death/male", "Death/female", "PCM/male", "PCM/female"),
       lty=c(1,1,2,2), col=c(2,1,2,1), bty='n')

Corrected legend:
legend(0, .8, c("Death/male", "Death/female", "PCM/male", "PCM/female"),
       lty = c(1,2,1,2), col=c(2, 2, 1, 1), bty='n')

Color = event type with red = Death, black = PCM
Line type = group with solid = male, dashed = female

**Comment by therneau** [comment]
Now fixed, thanks
