### ISSUE TITLE
help with installing 'survival' in R version 4.01

### ISSUE THREAD

**Issue by colleenburge** [therneau/survival#116]
I am now working in 

'R version 4.0.1 (2020-06-06) -- "See Things Now"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)'

I had used 'Survival' on a previous version of my computer but it would not work. So I uninstalled R and started over. Now I am not able to install survival, here is the error text I'm getting.

> install.packages("survival")

  There is a binary version available but the source version is later:
         binary source needs_compilation
survival 3.1-12  3.2-3              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘survival’

trying URL 'https://cran.rstudio.com/src/contrib/survival_3.2-3.tar.gz'
Content type 'application/x-gzip' length 7475152 bytes (7.1 MB)
==================================================
downloaded 7.1 MB

* installing *source* package ‘survival’ ...
** package ‘survival’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘survival’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/survival’
Warning in install.packages :
  installation of package ‘survival’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/77/1cjwcbr91cl8gdhlxnrbg5ww0000gn/T/RtmpKdpX9G/downloaded_packages’
> 

From here I am getting 'Error in library(survival) : there is no package called 'survival'

Help! :)

**Comment by therneau** [comment]
This is a question for the r-SIG-Mac mailing list.   (See the https://www.r-project.org/mail.html).  It is not an issue with survival; a quick google search shows that you likely have an install problem with xcode, but I am not a Mac expert.

**Comment by colleenburge** [comment]
Thank you for your help! I was able to go back to an earlier version of R and it works perfectly again.
