### ISSUE TITLE
Impossible to use type = 'interval2'

### ISSUE THREAD

**Issue by joeycouse** [therneau/survival#117]
Hello,

I am having an issue with the Surv() function. Looking at the source code seem like the function draws an error 'Wrong number of arguments for this type of survival data' whenever three arguments are presented e.g. (time1, time2, event, type = 'interval2'). However later the source, the code references arguments such as time2. Not sure what is going on but I think that part of the code is impossible to reach. 
 
code referenced below:

else {
        type <- mtype
	if (ng!=3 && (type=='interval' || type =='counting'))
		stop("Wrong number of args for this type of survival data")
	if (ng!=2 && (type=='right' || type=='left' ||  type=='interval2'))
		stop("Wrong number of args for this type of survival data")
	}

else {  #interval censored data
	if (type=='interval2') {
	    # convert to "interval" type, infer the event code
	    if (!is.numeric(time2)) stop("Time2 must be numeric")
	    if (length(time2) !=nn) 
		    stop ("time and time2 are different lengths")
            backwards <- (!is.na(time) & !is.na(time2) & time > time2)
            # allow for infinite times (important to do the backwards check
            #  first)
            time  <- ifelse(is.finite(time), time, NA)
            time2 <- ifelse(is.finite(time2), time2, NA)
            unknown <-  (is.na(time) & is.na(time2))
 	    status <- ifelse(is.na(time),  2,
		      ifelse(is.na(time2), 0,
		      ifelse(time==time2, 1,3)))
	    time <- ifelse(status!=2, time, time2)

**Comment by therneau** [comment]
This is correct behavior.  Read the help page for Surv.
