### ISSUE TITLE
Issues with number at risk from summary.survfit

### ISSUE THREAD

**Issue by ellessenne** [therneau/survival#119]
Hi,
I have a question regarding the `summary.survfit` function. See for instance the following example:

``` r
library(survival)
fit <- survfit(Surv(futime, fustat) ~ 1, data = ovarian)
summ <- summary(fit, times = seq(0, max(ovarian$futime), by = 365), extend = TRUE)
d <- data.frame(
  time = summ$time,
  n.risk = summ$n.risk,
  n.event = summ$n.event,
  n.censor = summ$n.censor
)
d$test <- d$n.risk + d$n.censor + d$n.event
d
#>   time n.risk n.event n.censor test
#> 1    0     26       0        0   26
#> 2  365     20       7        0   27
#> 3  730     10       5        4   19
#> 4 1095      4       0        6   10
```
<sup>Created on 2020-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was expecting the `test` column to be equal to `n.risk` at the previous time. Any idea on why that's not the case? 
My guess is that this happens when there are events (or censored observations) at the specific times passed to the `times` argument of `summary.survfit`. Any idea on how to fix it, or am I missing something obvious here?

Many thanks!

Alessandro

**Comment by therneau** [comment]
I has responded via email.   The numbers are correct.  The number at risk on day 365 includes an event that happened on day 365.  A censor on day 365 would be in the next interval, however.   Keeping track of < vs <=, correctly, is one of the challenges in the summary.survfit code.

**Comment by ellessenne** [comment]
I see, thanks for your reply @therneau!
