### ISSUE TITLE
Missing backslash in Surv Rd

### ISSUE THREAD

**Issue by ramiromagno** [therneau/survival#120]
Missing backslash in: https://github.com/therneau/survival/blob/787027105bcc3d06b2eac00d360bef65f5dce508/man/Surv.Rd#L149

line should be instead:

```R
\code{\link{survreg}}, \code{\link{lung}}. 
```

**Comment by therneau** [comment]
Thanks.  Now fixed on my master copy.  (This copy is a mirror of my mercurial repository).
