### ISSUE TITLE
survfit not working for competing risks when all observations censored

### ISSUE THREAD

**Issue by plana-ripoll** [therneau/survival#124]
survfit.formula gives an error when running for competing risks (not for regular Kaplan-Meier) and all observations are censored. Here is an example:
```{r}
# Fit Kaplan-Meier curve for event (pcm or death)
fitKM <- survfit(Surv(stop, event!='censor') ~1, data=mgus1,
                 subset=(start==0))

# Now consider competing events
fitCR <- survfit(Surv(stop, event) ~1,
                 data=mgus1, subset=(start==0))
```
Now let's assume I want to do the same for a dataset in which all observations are censored. I know it might seem strange to estimate survival curves when all individuals are censored, but it might happen when running automatically for several different datasets. It works ok with kaplan-meier, but not competing risks.

```{r}
# Now remove all events and keep only censored
mgus1 <- mgus1[mgus1$event == 'censor', ]

# Re-do the calculations, in which survival should be 100%
fitKM <- survfit(Surv(stop, event!='censor') ~1, data=mgus1,
                 subset=(start==0))

fitCR <- survfit(Surv(stop, event) ~1,
                 data=mgus1, subset=(start==0))
# Error in dimnames(events) <- list(count = tab1.levels, state = c(ystate,  : 
#  'dimnames' applied to non-array
```
I don't think this happened in previous versions of the package.

**Comment by therneau** [comment]
Now fixed in my master copy.  Yet another case of needing [ ,drop=FALSE] in one place.

**Comment by plana-ripoll** [comment]
Do you know when this fix will be available on CRAN? I am working on a server and I can only use CRAN packages unfortunately...
