### ISSUE TITLE
Confidence interval arguments have no effect in Turnbull estimator

### ISSUE THREAD

**Issue by jamesmyatt** [therneau/survival#125]
When using `survfit` for interval censored data, none of the arguments relating to the confidence interval appear to have any effect.

e.g.

```
survfit(
    Surv(duration_min, duration_max, type = "interval2") ~ 1, data = df,
    se.fit=F, conf.type="none", conf.int=0.5
)
```

produces exactly the same output (as far as I can tell) as without any of the optional arguments.

My R isn't great but I think it's related to this line. I assume that the `...` only passes the unmatched arguments, but all of these arguments were already matched, so their equivalents in `survfitKM` use the default values instead.

https://github.com/therneau/survival/blob/dd4bb4bca36e4876d8329c7b33ece11d93131072/R/survfitTurnbull.R#L190

**Comment by therneau** [comment]
Fixes

**Comment by jamesmyatt** [comment]
Thanks
