### ISSUE TITLE
Linear and nonlinear terms in coxph with P-spline

### ISSUE THREAD

**Issue by fintzij** [therneau/survival#127]
Hello,

Is there a reference that I could consult that provides the details for how the linear and non-linear effects in a Cox proportional hazards model with a P-spline term are derived? I'm trying to piece together what is actually going on in the print method, but without much success.

Thanks,
Jon

**Comment by therneau** [comment]
For the evenly spaced cubic spline basis use by pspline,  sum(coef[i] * basis[,i]) is linear if and only if the set of coefficients is linear.   I don't know a reference per se, it is just a fact about the basis.   Thus any linear contrast in the coefficients is a test for linearity, and the leftover a test for non-linearity.   Follow up with email if you want more info.
