### ISSUE TITLE
Survfit - Greenwood

### ISSUE THREAD

**Issue by tku23** [therneau/survival#129]
Hi there,

I have tried looking everywhere online but couldn't find an answer to this. I am trying to use "Greenwood" in survfit but it appears the error argument is no longer used. Is there a rationale for removing Greenwood or is there a way for me to incorporate it?

In addition, can I still use type="kaplan-meier" in the survfit formula? 

Thanks in advance.

**Comment by therneau** [comment]
Greenwood has been the default for the KM since forever.   No one used the other options, in fact, and I finally deleted them to make the code simpler.   The type argument has been replace by stype and ctype and removed from all documentation.   Why do you want it?

**Comment by tku23** [comment]
Thanks for the clarification. I'm new to R and trying to compute the code below. 
 
`survfit(formula, type="kaplan-meier", error="greenwood", conf.type="log-log")`

Based on your reply, I could just simplify it and compute the new code below which will achieve the same thing (without using stype and ctype)? Many thanks...

`survfit(formula, conf.type="log-log")`

**Comment by therneau** [comment]
The ctype argument controls computation of the cumulative hazard component, stype controls computation of the surv or pstate component of the curve.   For the survfit.formula method, the default for stype=1.
