### ISSUE TITLE
Call `survexp` inside a function with `rmap` as argument

### ISSUE THREAD

**Issue by qmarcou** [therneau/survival#135]
Dear @therneau ,
I have been trying to write a function that performs some computation using a call to `survival::survexp`. In order to keep this function somewhat flexible I'd like to pass it the `rmap` argument. However because `survexp` expects a possibly lazy evaluated expression I have been struggling with finding the correct way to do this. I'll propose a possible fix for `survexp` below. Here's a sketch of what i'd like to do:
```r
my_func<-(df,times,ratetable,rmap){
  return(survexp(formula = ~ 1, data=df,
                            rmap = rmap ,method = 'ederer',times=c(times), ratetable = ratetable))
myfunc(df,times,ratetable,rmap=list(year=year, sex=sex,age=age))
}
```   
However doing so I'd systematically get the following error upon calling `my_func`:
> Invalid rcall argument

which is produced by this piece of `survexp`:
```r
rcall <- substitute(rmap)
if (!is.call(rcall) || rcall[[1]] != as.name('list'))
    stop ("Invalid rcall argument")
```
Now I could pinpoint in debug mode, that because `survexp` always calls substitute I would always obtain an `rcall` of type 'symbol' and of value "rmap", meaning I have lost all the information about the `rmap`, provided in `my_func`. This happens no matter what happens in `my_func` (e.g using substitute to pass on the correct expression or call to survexp).

Here is some minimal code to reproduce this issue:
```r
test_func<-function(rmap){
 rcall <- substitute(rmap)
  if (!is.call(rcall) || rcall[[1]] != as.name('list'))
    stop ("Invalid rcall argument")
}

test_func_wrap<-function(rmap){
  test_func(rmap=rmap)
}
test_func_wrap(list(year=year))
```
I have been playing around and I could not find any solution that would allow `test_func` to pass the test without having to modify test_func. (Disclaimer: I am however not very experienced in R, and quite confused by the whole substitute/quote/eval etc family of functions)
The following code, however, seems to work:

```r
test_func<-function(rmap){
  if(is.call(rmap)) rcall<-rmap # first check whether the user has provided a call object for rmap
  else rcall <- substitute(rmap)

  if (!is.call(rcall) || rcall[[1]] != as.name('list'))
    stop ("Invalid rcall argument")
}

test_func_wrap<-function(rmap){
  rmap=substitute(rmap) # make the substitution where the user wants to
  test_func(rmap=rmap)
}
test_func_wrap(list(year=year))
```
Once the substitution has occurred in the first layer function, the call can be passed as any other R object through several function layers. With this fix, the user is allowed to either use `survexp` in command line and define `rmap` as usual, or pass a call object that constructs a list.

I'd also like to add one small thing:
- The error message might not be clear for the user if he's not dwelling on the code, "Invalid rmap argument" may be clearer

Again thank you very much for this fantastic package!
best regards

**Comment by qmarcou** [comment]
Sorry I realized after a few experiments that my "solution" works only for 1 function calling and not nested function calls.
After some reading on R and NSE, premise etc I realize I should be using substitute (+eval) at the function call time:
```r
my_func<-(df,times,ratetable,rmap){
  return(eval(substitute(survexp(formula = ~ 1, data=df,
                            rmap = rmap ,method = 'ederer',times=c(times), ratetable = ratetable))))
}
myfunc(df,times,ratetable,rmap=list(year=year, sex=sex,age=age))
```
No change needed to `survexp` to make it work then.
I understand the fact that most people will call `survexp` interactively and why you would like to use NSE by default. Still it would be nice to have access to another version (or escape hatch as described [here](http://adv-r.had.co.nz/Computing-on-the-language.html#calling-from-another-function)) allowing to pass a quoted expression for functional programming.
 best regards

**Comment by therneau** [comment]
This type of question actually belongs on r-help.  The survexp function needs to defer evaluation of the rmap argument, and needs a copy of the unevaluated form of rcall.  
  When you call survexp, inside your function, the use of  the variable "rcall" causes it to be evaluated.  What you want is a way to pass the unevaluated form of your rcall argument, forward to another function.  I don't know how to do that, but I will guess that someone else does.

**Comment by qmarcou** [comment]
Dear @therneau ,
This was indeed more of a general misunderstanding about R than an issue with `survexp` in the end (I however did not realize this at the time of posting, my apologies). 
The solution to pass the unevaluated form of `rmap` is given in my second post. This is the general solution for functions using NSE without possible escape from it according to [Advanced R](http://adv-r.had.co.nz/Computing-on-the-language.html#substitute). 
Since my problem is solved I'll close the issue. I'd however like to restate that the error message for incorrect `rmap` argument is confusing since the error statement is about `rcall` an object created inside the function and unknown to the user.
Again thank you very much for this great package and the time you took to answer,
best regards
