### ISSUE TITLE
Partial argument match of `along` to `along.width`

### ISSUE THREAD

**Issue by schloerke** [therneau/survival#136]
From `?base::seq`:

```r
 seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
     length.out = NULL, along.with = NULL, ...)

 seq.int(from, to, by, length.out, along.with, ...)

 seq_along(along.with)
```

-----------------

I found the partial argument match within 

```
 6. survival:::`[.survfit`(x, mo) 
 8. base::seq(along = x$time)
```

I am able to repro the partial match by setting the options:

```r
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE
)
```

There are many more usages of `seq(along = x)`, but I didn't know if they were using the standard `base::seq()`.

**Comment by therneau** [comment]
This is interesting -- normally R CMD check complains about partial matches (it has for several other routines).   You are correct that all these are calls to the base seq, and per the "rules" I should be using a full argument name.
Now fixed in my local (master) copy.

**Comment by schloerke** [comment]
Thank you!

I think it is related to `seq()` being an S3 method. For static code checking, the `along` is matching to `...` which would not produce any errors.
