### ISSUE TITLE
changes to m* type handling in survreg.S

### ISSUE THREAD

**Issue by Diapadion** [therneau/survival#14]
I updated the package and now my left-truncated AFT models don't work any longer. It appears to be down to this code:

    if (type== 'counting') 
        stop ("start-stop type Surv objects are not supported")
    if (type=="mright" || type=="mcounting") 
        stop("multi-state survival is not supported")

So no form of counting / left-truncated data appears to be supported now. Why was this changed, when it appeared to work fine before? Is it methodologically incorrect to use an older version of this code to continuing running left-truncated AFT models?

**Comment by therneau** [comment]
Left truncated AFT models have never been supported, nor have counting process models.  
Such data may once have slipped through in error.  The correct likelihood for a counting 
process model is not easy.   I've often thought that it would be a nice addition, but have 
not had a data set that requires it.  Almost all additions to the survival package are 
motivated by a data set --- urgent need is what moves a project from thinking to action.

Terry T.

**Comment by Diapadion** [comment]
Hmmm, okay. That is concerning for my results, but also interesting. What was happening in the past when I used mcounting type Surv data in AFT models? The fit objects seemed to be doing everything as I would have expected.
