### ISSUE TITLE
is.ratetable crashes for 0 valued ratetable in verbose mode

### ISSUE THREAD

**Issue by qmarcou** [therneau/survival#141]
Dear @therneau ,
I have stumbled upon a small bug in `survival::is.ratetable`. For some reason I needed to pass a zero valued ratetable (no mortality) to some piece of code using `survexp` under the hood. It turn out this makes `survexp` return an error instead of returning survival values equal to 1 (depending on how I build my zero valued ratetable).
Trying to diagnose, I have tried to use `is.ratetable` in verbose mode but it returns an error, here is a minimal non working example:
```r
tmp<-survexp.us # take a ratetable template
print(is.ratetable(tmp)) # TRUE
tmp<-tmp*0 # set all mortality values to 0
print(is.ratetable(tmp)) # FALSE
print(is.ratetable(tmp,verbose=TRUE)) # Error in is.ratetable(tmp, verbose = TRUE) : object 'type' not found
```  

As a side note, for some reason using `tmp[]<-0` (which is much cleaner) instead of `tmp<-tmp*0` returns a correct ratetable according to `is.ratetable` (I guess upon multiplying by 0, I also modify covariates breaks/values?).

best regards

**Comment by therneau** [comment]
That is not a bug.   The command temp <- survexp.us * 0 removes all the attributes, and so the result is no longer a rate table.   This is done by R, not me, and is the right default.
