### ISSUE TITLE
Inconsistency for calculating "fleming-harrington" standard errors

### ISSUE THREAD

**Issue by bkwrmacb** [therneau/survival#142]
Hello,

In version 2.43-3 of survival (R 3.5.3) when calculating fleming-harrington for survfit at the maximum time point (0 patients left) the standard errors reach infinity.  When we tried to recalculate using survival 3.2.10 (R 4.0.5) it provides standard errors for these (not-infinity) is there a place I could find the documentation for the calculation differences?

**Comment by therneau** [comment]
There have been hundreds of updates since 2.43, and no way that I remember them.  If I had to guess, it would the use of the Aalen variance  sum(1/nrisk^2) instead of the Greenwood term of sum(1/ (nrisk * (nrisk -ndeath)).   The latter can give a 1/0 term.
