### ISSUE TITLE
cox.zph crashes R Studio with coxme model

### ISSUE THREAD

**Issue by bfazen** [therneau/survival#146]
I seem to get a consistent failure when using cox.zph() on coxme model fits.  The underlying code for cox.zph looks as though coxme models are acceptable inputs to this function, but it does not seem to work (I can use coxph models fine).  There is unfortunately no other error information that I see, as R studio simply aborts the session, and so it is difficult to troubleshoot what is going wrong.  

platform x86_64-apple-darwin17.7.0   
R version 3.6.1 (2019-07-05)
survival 3.2-11
coxme 2.2-16

**Comment by therneau** [comment]
A covariate that was a constant was included in the model (everyone was female), which caused a division by 0 when scaling x, and things went to hell from there.   A check and error message has been added.
