### ISSUE TITLE
Add 'anova' class to `anova.survreg()` objects 

### ISSUE THREAD

**Issue by ddsjoberg** [therneau/survival#149]
Hello!

I've been working with the output from the `anova()` function recently, and I've noticed that the output from `anova.survreg()` has class `'data.frame'`. Nearly all other objects from `anova()` have class `c('anova', 'data.frame')`, including the other modelling function in the survival package, such as `coxph()`. The lack of the `anova()` class has caused some issues downstream working with these objects.

Can the class `c('anova', 'data.frame')` please be added to the output of `anova.survreg()`?

Thank you! Examples below

``` r
library(survival)

# 'anova' class not added ------------------------------------------------------
m1 <- survreg(Surv(time, status) ~ sex, data = lung, dist = "weibull", scale = 1) 
class(anova(m1))
#> [1] "data.frame"

m2 <- survreg(Surv(time, status) ~ sex + ph.ecog, data = lung, dist = "weibull", scale = 1) 
class(anova(m2))
#> [1] "data.frame"

# for other models, 'anova' is included in the class ---------------------------
m3 <- coxph(Surv(time, status) ~ sex, data = lung) 
class(anova(m3))
#> [1] "anova"      "data.frame"

m4 <- lm(time ~ sex, data = lung) 
class(anova(m4))
#> [1] "anova"      "data.frame"

m5 <- glm(as.logical(ph.ecog) ~ sex, data = lung, family = binomial) 
class(anova(m5))
#> [1] "anova"      "data.frame"

# system info ------------------------------------------------------------------
R.version.string
#> [1] "R version 4.1.0 (2021-05-18)"
packageVersion("survival")
#> [1] '3.2.11'
```

<sup>Created on 2021-06-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by therneau** [comment]
Now fixed in my master copy.  I was assuming that stat.anova preserved the class.
Thanks for the note.

**Comment by ddsjoberg** [comment]
Thank you kindly!
