### ISSUE TITLE
problem with new changes to Surv function

### ISSUE THREAD

**Issue by hemonika** [therneau/survival#15]
When I changed the version of the package from 2.40-1 to 2.41-1 I suddenly got a problem with running the following function.

`surv.curve <- survfit(Surv(min_length_of_treat, max_length_of_treat, type = "interval2") ~ doseadjust_5lev,
                      data = cohmed.bio1)`

It produced the error 

> Error in wtmat %*% diag(jumps) : non-conformable arguments

that I could trace back to the` survfit` function. This function was not updated for a long time, but the `Surv` function. So I looked into the changes there, that means in the commit

[Error in detecting INF values.](https://github.com/therneau/survival/commit/757628385e1dc5589d8e9a340e8790a73156a992)

and realized that the changes in this commit changed the logic.
I tried to reestablish the old logic in the following two lines (also using the `is.finite` function):

`            time <- ifelse(!is.finite(time) & sign(time) == 1, NA, time)`
`            time2 <- ifelse(!is.finite(time2) & sign(time) == -1, NA, time2)`

When I replaced the two lines in a local version of the `Surv` function I could run my above function again **without error**.

So I wanted to ask if the logic in the `Surv` commit was changed by chance or by intention. If by chance you could maybe update it further with my two lines of code?

**Comment by therneau** [comment]
The change was on purpose, and a ran a long test suite after doing it.  That does not mean 
that I don't have a mistake, but I cannot chase down your problem without data.

Please send notes directly to me (therneau@mayo.edu), since I rarely log into github.

Terry T.
