### ISSUE TITLE
Is it okay to recenter dummy variables corresponding to factors in `coxph`?

### ISSUE THREAD

**Issue by dwuab** [therneau/survival#150]
In my use case, there are ~10000 observations and ~200 variables most of which are not factors. If I don't set the `nocenter` argument of `coxph`, `coxph` will spend ~0.6s in finding out which variable should be recentered, while just ~1.6s in fitting (coxph.fit). As I am going to scale my computation, I would like to eliminate that ~0.6s for checking.
The documentation of coxph states that "The practical consequence of the default is to not recenter dummy variables corresponding to factors." which seems to suggest recentering dummy variables is a bad idea.
Is it true? If yes, why?
Thanks!

**Comment by therneau** [comment]
Recentering is important from a numerical analysis point of view, whenever there is a variable with a huge mean compared to its std.   An example that often arises is the use of a Date variable as a covariate when the observations cover only a  couple of months: then x will have a mean of 18000 and a std of about 15, and overflow of exp() is a common result.     If you are being careful on your own then feel free to not recenter.

**Comment by dwuab** [comment]
Thanks for your reply. I understand the purpose of recentering. However, I original question is actually, is there cases where we **SHOULD NOT** recenter?
