### ISSUE TITLE
Error with: Predict with pspline degree 1

### ISSUE THREAD

**Issue by L3vL** [therneau/survival#153]
Hello,

There is an Error with predict() and pspline() if the argument "degree" is not the default "3" (i.e. 1,2,6,7,9). 
It says: 

> "Error: variable 'pspline(age, degree = 1)' was fitted with type "nmatrix.10" but type "nmatrix.12" was supplied"

However, it works when degree is 3 (default).

How can I fix this issue? Is there a workaround?

Thanks!

Best,
L

Here a reproducible example:

#Packages
library(RMThreshold)
library(survival)
library(dplyr)
#Generation of a df
set.seed(123)
age<-15:100
youngEU<-seq(100,30, length.out=match(30,age))
youngEU_c<-youngEU
middleEU<-rep(youngEU_c[length(youngEU_c)],length(age[match(31,age):match(65,age)]))
middleEU_c<-middleEU
elderlyEU<-seq(middleEU_c[length(middleEU_c)],60,length.out=length(age[match(66,age):match(100,age)]))
elderlyEU_c<-elderlyEU
age_eu_df<-data.frame(age=age,Euvalue=c(youngEU_c,middleEU_c,elderlyEU_c))
agerepeat<-rep(age_eu_df$age,10000)
eurepeat<-rep(age_eu_df$Euvalue,10000)
eurepeat_noise_02<-RMThreshold::add.Gaussian.noise(as.matrix(eurepeat),mean = 0, stddev = 10, symm = F)
eurepeat_noise_02[eurepeat_noise_02>100]<-100
eurepeat_noise_02[eurepeat_noise_02<0]<-0
eurepeat_noise_03<-eurepeat_noise_02[,1]
largedataEU_age<-data.frame(age=agerepeat,Euvalue=eurepeat_noise_03)
traindata<-largedataEU_age[sample(1:nrow(largedataEU_age),3000),]

#Now modelling
degree1<-lm(Euvalue~pspline(age,degree = 1),data=traindata)
degree2<-lm(Euvalue~pspline(age,degree = 2),data=traindata)
degree3<-lm(Euvalue~pspline(age,degree = 3),data=traindata)
degree4<-lm(Euvalue~pspline(age,degree = 4),data=traindata)
degree5<-lm(Euvalue~pspline(age,degree = 5),data=traindata)
degree6<-lm(Euvalue~pspline(age,degree = 6),data=traindata)

#New data
newdatapredict<-15:100
#Now predict
degree1_pred<-predict(degree1,data.frame(age=newdatapredict))
degree2_pred<-predict(degree2,data.frame(age=newdatapredict))
degree3_pred<-predict(degree3,data.frame(age=newdatapredict))
degree4_pred<-predict(degree4,data.frame(age=newdatapredict))
degree5_pred<-predict(degree5,data.frame(age=newdatapredict))
degree6_pred<-predict(degree6,data.frame(age=newdatapredict))

**Comment by therneau** [comment]
This was an oversight: I have neglected to include 'degree' in the makepredictcall arguments.   Now fixed.
