### ISSUE TITLE
`survfit`'s NP Median Calculation

### ISSUE THREAD

**Issue by MetzgerSK** [therneau/survival#156]
Two clarification questions about `survfit`'s non-parametric median calculation, one minor, one major.  Depending on the answers, there may be an error in `survfit`'s calculations.  After cleaning up my MWEs, I've come to suspect that the two questions may be different sides of the same coin.  (Used to test: `survival` 3.2.11.)

Based on `print.survfit`'s documentation, it seems like `survfit` should be kicking out the KM-based median for a non-parametric estimate, not the naïve median:

<blockquote>
(From <code>?print.survfit</code>)

The median and its confidence interval are defined by drawing a horizontal line at 0.5 on the plot of the survival curve and its confidence bands. The intersection of the line with the lower CI band defines the lower limit for the median's interval, and similarly for the upper band. If any of the intersections is not a point the we use the center of the intersection interval, e.g., if the survival curve were exactly equal to 0.5 over an interval. When data is uncensored this agrees with the usual definition of a median.
</blockquote>

### Minor Q ###
I understand the KM-based median's definition to be (Klein and Moeschberger 2003, 33):
<blockquote>
<img src="https://render.githubusercontent.com/render/math?math=Q_50 = \inf\left\{ t : S(t) \leq 0.5\right\}">
</blockquote>

__:question:: Isn't using the "the center of the intersection interval" at odds with the infimum portion of the KM-based median's definition?__

### Major Q ###
I noticed the bit about the intersection interval's center because of another, larger problem I came across with a different toy dataset (attached to GH issue).  It appears that `survfit` kicks out the naïve median, not the KM-based median that its documentation suggests (see "Major Q" summarized output below).

__:question:: Is `survfit` supposed to be computing the naïve median or the KM-based median?__

I now suspect these two questions are potentially interlinked because, when I change whether subject 6 is right censored in the minor Q MWE, `survfit`'s median value changes, but Stata's doesn't.

#### Minor Q
```
// >> R (trimmed)
# Variant 1: subj 6 fails
## Median according to survfit: 5.5
## Naïve median: 5.5

# Variant 2: subj 6 doesn't fail
## Median according to survfit: 6
## Naïve median: 5.5

// >> Stata (trimmed)
# Variant 1: subj 6 fails
## Median according to stsum: 4
## Naïve median: 5.5

# Variant 2: subj 6 doesn't fail
## Median according to stsum: 4
## Naïve median: 5.5
```
#### Major Q
```
// >> R (trimmed)
# Median according to survfit: 0.3959424
# Naïve median: 0.3959424
# Manual KM-based median: 0.392

// >> Stata (trimmed)
# Median according to stsum: 0.3924462
# Naïve median: 0.39594242
# Manual KM-based median: 0.39244622
```
---
#### Minor Question
```r
rm(list=ls())
library(survival)

# Toy data where half of the subjects fail by
# t=4, but next subj doesn't fail until t=7
minorQ <- data.frame(id=1:10,
                     t=c(1,2,2,4,4,7,8,10,12,15),
                     fail=rep(1,10))
minorQ

# VARIANT 1
## Median according to survfit
survfit(Surv(t,fail)~1, data=minorQ)

## Naïve median
median(minorQ$t)
#****************************************
# VARIANT 2
## Censor subject 6
minorQ[6,"fail"] = 0

## Median according to survfit
survfit(Surv(t,fail)~1, data=minorQ)

## Naïve median (will be same as variant 1)
median(minorQ$t)
```

#### Major Question
```r
rm(list=ls())
library(survival)
library(broom)
library(dplyr)

# Load
testData1 <- read.csv("testData1.csv") # attached to GH issue

# Median according to survfit
sf <- survfit(Surv(t,fail)~1, data=testData1)
print(sf, digits=7)

# Naïve median
median(testData1$t)

# Find KM-based median manually: find smallest t for which S(t)<=0.5
tidy(sf) %>%
    filter(estimate<=.5) %>%
    summarize(Q_50=min(time))
```

#### Minor Question
```stata
clear *

// Toy data where half of the subjects fail by
// t=4, but next subj doesn't fail until t=7
mata dat = (range(1,10,1), (1,2,2,4,4,7,8,10,12,15)', J(10,1,1))
mata dat

// Bring data into main Stata memory
getmata (id t fail)=dat, double
stset t, fail(fail==1)

// VARIANT 1
* Median according to stsum
stsum

* Naïve median
qui sum _t, detail
di `r(p50)'
*****************************************
// VARIANT 2
* Censor subject 6
replace fail = 0 in 6
streset

* Median according to stsum
stsum

* Naïve median (will be same as variant 1)
qui sum _t, detail
di `r(p50)'
```
#### Major Question
```stata
import delimited "testData1.csv", clear  // attached to GH issue
stset t, fail(fail==1)

// Median according to stsum
stsum

// Naïve median
qui sum _t, detail
di `r(p50)'

// Find KM-based median manually: find smallest t for which S(t)<=0.5
sts gen sKM = s
qui sum _t if(sKM<=0.5)
di `r(min)'
```

**Comment by therneau** [comment]
First:  I do not see any files attached to the issue, so the "attached to GH issue" line remains unclear.   and I thus can't address your  major question.   Can you send me the file (therneau@mayo.edu).     The line "after cleaning up my MWE's ...": what is an MWE?

As to the minor question.   We decided to make the median for a survival curve agree with the standard definition of a median, for those cases where it makes sense to do so.   This was done over a decade ago as a result of a multi-party discussion.  The argument that survfit should mimic the widely accepted definition of a median, when possible, was persuasive.   Data sets where the issue arises are very rare, however.

This behavior is documented in the help file, as you point out.  Your two examples using minorQ perform exactly as advertised.
In the first fit the CDF has a horizontal line at .5 from 5 to 6 (median 5.5) and in the second from 4 to 8 (median 6).
I disagree quite strongly with the assertion that this is an error, simply because  Stata decided to use a different default, or that a particular textbook didn't think through this case.   

(I have now fixed the small typo and it reads "is not a point then we use" instead of "the we use", but I doubt this confused anyone.)

**Comment by MetzgerSK** [comment]
Thanks for the clarification on all points.  This seems like an instance of "given the definition I was using from Klein and Moeschberger, I read the help file with what I was expecting to see in mind."  I knew Stata's `stsum` used the Klein and Moeschberger definition for quantiles, which is why I included its code and output for comparison.  

Given your explanation, what I was seeing as a potential bug is, in fact, the intended behavior.  Keeping your explanation in mind, I can now absolutely see how `?print.survfit`'s documentation explains as much without contradicting itself.

Thanks again for taking the time to contextualize and explain.

(Also, apologies: I have no idea where the attachment went.  I can send it along in an email, sure, but in light of what you've explained, the behavior's intended.  It just so happens that the midpoint of the CDF = 0.5 plateau for that example comes out to be the naïve median.)
[testData1.csv](https://github.com/therneau/survival/files/6992643/testData1.csv)
