### ISSUE TITLE
Why does the cox model overpredict the risk of the population?

### ISSUE THREAD

**Issue by flippercy** [therneau/survival#158]
Hi @therneau:

I have a question regarding the usage of survival probability ($surv) returned by the survfit object.

I built a coxph model and then used it to calculate the expected # of events within each time window (month in my case) of the modeling data through survfit(). Specifically, for each record, I calculated its probability of event during time window T as $surv[T-1] - $surv[T]; finally, I added the individual probabilities together per time window as the expected # of events within each time window.

With this method, I found out that the coxph model overpredicted the risk (probability of event) at the population level. For example, in the modeling data the actual overall cumulative probability of event in the first six months is 0.167 (actual # of events / # of records) but I got 0.194 as predicted using the method above; for the first twelve months is 0.296 vs 0.334, 24 months is 0.466 vs 0.529. I understand that the model won't be perfect but am still surprised that there is such a big gap with the modeling data itself.

Is there anything wrong with the method I used for the calculation? If not, do you know how to fix the overprediction?

Appreciate your help!

**Comment by therneau** [comment]
You have to give me a real example: the code that you used, even better if it includes a sample data set.   Frankly, I am guessing that you have a mistake -- this doesn't happen to me.    But a bug in my code is possible (always).
