### ISSUE TITLE
Issue with creating survival object

### ISSUE THREAD

**Issue by benjaminwnelson** [therneau/survival#159]
Hello, I have the following code.

`survival_object <- Surv(time = data_final_survival$time, event = data_final_survival$status)
head(survival_object, 80)`

The head function gives output that looks like the following. Any ideas why it's not showing how long the subject was tracked for and whether they are censored? Thanks!
![Screen Shot 2021-08-31 at 12 48 47 PM](https://user-images.githubusercontent.com/36683142/131543546-3b5a2396-580d-4066-83af-fd53a596b698.png)

**Comment by therneau** [comment]
I have never created a head() method for survfit objects.   I'd be very interested in what you think it should print?   
That isn't a snarky question, and I'm happy to have other's opinions.   
The hardest case would be a survfit  object with dimension (2,3, 2), i.e., it contains 12 curves.   What is a good summary?

Terry T
