### ISSUE TITLE
Support for piecewise constant exponential model

### ISSUE THREAD

**Issue by hherrada** [therneau/survival#16]
I am new to survival analysis. I have greatly benefited from the package and your book in the learning process. Thank you.

I have 2 questions. 

1) Is support for the piecewise constant exponential model in the pipeline for future releases?

2) I would like to estimate a multi-state model with piecewise constant exponential baseline hazards, time-varying covariates (entering the hazard function as exp(B * X_t)), and a frailty term. Are you aware of an R package that would allow me to fit such a model? I am modeling credit transitions for a company.

I appreciate any guidance you can provide.

**Comment by therneau** [comment]
I have never had a need for peicewise constant hazards.  The surival package consists 
almost entirely of things that I have needed at one time or another for a medical research 
study. (Medical research is my real job, and there are only so many hours in a day.)  So 
no, it is not in the pipeline.

I would suggest you look at the survival task view, which is in the upper left menu on the 
CRAN page.  There are many many package on CRAN, many in response to important methods 
that never made to my pipeline.  I make no claim that the survival package has everything, 
or even most of everything, that we need.


Terry T.

**Comment by adibender** [comment]
@hherrada Piece-wise exponential models (which have piece-wise constant hazards) are essentially Poisson GLMs/GAMs, which you can fit with `glm`/`gam` functions after appropriate data transformation. 
I'm currently write a package that facilitates this data transformation + other convenience functions. 
There are also lots of vignettes that explain usage of PEMs
You can find the package here: https://github.com/adibender/pam 
Install using `devtools::install_github("adibender/pam", build_vignettes=TRUE)` and 
look at vignettes with `browseVignettes(package="pam")`. You can post issues [here](https://github.com/adibender/pam/issues) if you have any more questions
