### ISSUE TITLE
Appropriate Statistical Test

### ISSUE THREAD

**Issue by awaldman123** [therneau/survival#160]
I sent this via email before stumbling upon this github page and thought maybe this was a better forum for my question (my apologies if not):

I am attempting to run an analysis looking at whether the location and type of a particular lesion predicts age at death. It is important to note that all individuals are deceased and the information regarding lesions was gathered post-mortem. I have data on the presence, number, and proportional area of lesions of varying types (Type 1, 2, and 3) in varying locations (Region 1, 2, and 3) for each individual. I was advised to run a cox proportional hazard model to look into the relationship between lesion types/location and time to death. Given that the data is nested (ie lesion types within regions) I thought I would need to use the coxme package to fit a mixed effects version of the cox model. However, I was looking at the following example: https://stats.idre.ucla.edu/r/dae/mixed-effects-cox-regression/ and my data doesn't seem to fit as my predictors are not repeated measures by virtue of being gathered at multiple time points but rather I have information on lesion presence/number/area of different types and at different locations and want to understand the relationship with time to death. Therefore, would a regular cox proportional hazard model using the survival package be more appropriate where I include 9 predictors (ie Presence/Number/Area of Lesion Region 1 of Type 1, Lesion Region 2 of Type 1, Lesion Region 3 of Type 1, Lesion Region 2 of Type 1, Lesion Region 2 of Type 2, Lesion Region 2 of Type 3, Lesion Region 3 of Type 1, Lesion Region 3 of Type 2, and Lesion Region 3 of Type 3). I guess I was just concerned about the possible collinearity of these predictors since they are a repeated measure on each individual but I'm interested in the relationships with particular lesion types/locations. This is all quite new to me and any insights you could provide in pointing me in the right direction would be much appreciated.

**Comment by therneau** [comment]
This is a statistical question, not a code question; so not the usual target of this list.
You have correlated predictors, not correlated outcomes.  (Death happens at most once).  Mixed effects models do not apply.
Co linearity of predictors is an old, old problem in statistics, and affects all model types.
