### ISSUE TITLE
print.survfit.Rd and Median Calculation Description

### ISSUE THREAD

**Issue by DarioS** [therneau/survival#163]
Would it be worthwhile to add an explicit sentence that deals with a scenario when there are insufficient events and the median is `NA`? I have seen a couple of questions on Stack Exchange about this. I have also looked at a couple of textbooks and neither of the two I looked into dealt with this edge case. My post-doc colleague didn't believe me when I said the median is undefined.

**Comment by therneau** [comment]
I've added a comment to the print.survfit help page per your suggestion -- quantile.survfit already had discussion of this.   I don't want to add  printed warning, such reminders get annoying very quickly .
