### ISSUE TITLE
Documentation error in for `gbsg`

### ISSUE THREAD

**Issue by chendaniely** [therneau/survival#164]
The documentation for the `gbsg` dataset has the following text under "Usage":

```
gbsg
data(cancer, package="survival")
```

Looks like a simple copy/paste error, where it should read `data(gbsg, package="survival")` instead.
I got really confused when looking at the column definitions and realized nothing matched up.

I'm not sure what the build process for the documentation, but it seems like I might be able to manually edit the `gbsg.Rd` file:  https://github.com/therneau/survival/blob/95222ae5b55e68a043448d79b883c2e6760a1bb3/man/gbsg.Rd#L12

If that's the way to fix it, I can submit a PR change.

**Comment by therneau** [comment]
The documentation is correct as it stands.   (Try testing it: start an R session, don't load survival, and type that command.  You will find that it works.)

To save space, several of the cancer data sets are packed into a single .rda file; named "cancer.rda" of course.
