### ISSUE TITLE
`clogit()` breaks before showing a warning

### ISSUE THREAD

**Issue by danielinteractive** [therneau/survival#165]
In the below example `clogit()` breaks just before showing a warning, inside `coxexact.fit()`.
This happens both on the CRAN version (3.2-13) as well as the latest development version here on github (3.2-14).

Error observed:
`Fehler in if (any(infs)) warning(paste("Loglik converged before variable ",  : 
  Fehlender Wert, wo TRUE/FALSE nötig ist`
(sorry for the German here :-), but basically missing value where there should be a logical flag)

Reprex: (sorry, could not find a shorter one)
```r
library(survival)

df <- data.frame(
  y = c(
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
    TRUE, TRUE, TRUE, TRUE, TRUE
  ),
  x = factor(c(
    2L, 1L, 2L, 2L,
    2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L,
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 2L,
    2L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L,
    1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L,
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L,
    2L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L,
    2L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,
    2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L
  )),
  strat = factor(c(
    1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 2L,
    2L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 2L, 2L, 1L, 1L, 2L, 2L,
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 2L,
    2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 1L,
    2L, 1L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 1L, 1L,
    1L, 2L, 1L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L,
    1L, 1L, 2L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L,
    1L, 1L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L
  ))
)
clogit(formula = y ~ x + strata(strat), data = df)
```

Session info:
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_CH.UTF-8       
 [4] LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survival_3.2-14

loaded via a namespace (and not attached):
[1] compiler_4.1.1  Matrix_1.3-4    tools_4.1.1     remotes_2.4.0   splines_4.1.1   grid_4.1.1     
[7] lattice_0.20-44
```

**Comment by therneau** [comment]
Take a quick look at the data:
> with(df, table(x, y, strat))
, , strat = 1

   y
x   FALSE TRUE
  1     1   11
  2     0   43

, , strat = 2

   y
x   FALSE TRUE
  1     2   19
  2     0   54

For the exact partial likelihood, the MLE estimate of the coefficient is infinite if one of the two groups has a 100% event rate, which is true for both strata.   (Not true for the Efron or Breslow approximations, but it also true for a binomial glm).
It is easy to check this out by looking at the first 10 iterations:

df$zero <- rep(0, nrow(df))   # add a dummy variable
nr <- matrix(0, 10, 3,
             dimnames= list(1:10, c("beta", "loglik", "se(beta)"))) 
options(warn= -1)
for (i in 1:10) {
    tfit <- coxph(Surv(zero, y) ~ x + strata(strat), df, iter=i, ties="exact")  # same fit as clogit
    nr[i,] <- c(tfit$coef, tfit$loglik[2], sqrt(tfit$var))
}
plot(nr[,1], nr[,2], xlab="Beta", ylab="Loglik")

Likeihood functions are expected to be quadratic near the peak, but this is one asymptotes to a line.   I have learned over the years that one of 3 things will occur when there is an infinite solution; it is  a race
1. The likelihood converges, i.e., the iteration's change is less than the convergence criteria  (950 out of 1000)
2. The coefficient becomes large enough that exp(X beta) overflows  (47 out of 1000)
3. The information (variance) matrix becomes effectively singular.        (3 out of 1000)

You have found an example of case 3 -- use print(nr) to see it.  For almost all the paths through the code I have checks for 2 and 3 above, but the exact partial likelihood does not yet have a check for case 3.  I need to copy that logic into this section as well (src/coxexact.c).  As you might guess, case 3 was the last to be appreciated.

**Comment by danielinteractive** [comment]
Thanks a lot @therneau for the explanations! And thanks in advance for checking this rare case in the code, it will improve the user experience further.

**Comment by therneau** [comment]
The issue has now been repaired.
