### ISSUE TITLE
Error when plotting confidence intervals for cumulative hazard

### ISSUE THREAD

**Issue by ellisdoro** [therneau/survival#169]
Confidence intervals are not plotting for cumulative hazard functions as they did in earlier versions.  It appears as though the `std.chaz` variable is not being set.  When I set this variable manually to the log standard error, I can get the confidence intervals to plot for the cumulative hazard function.

For example, when using the `rats` dataset:
```{r}
coxphmod<-coxph(Surv(time,status)~sex+rx,data=rats)
S.phmod = survfit(coxphmod,newdata=data.frame(rx=c(1),sex=c("m")),conf.type="log-log")
plot(S.phmod,conf.type = "log-log",cumhaz = TRUE)
```

I get the following error message:
```{python,color="red"}
Error in plot.survfit(S.phmod, conf.type = "log-log", cumhaz = TRUE) : 
  object does not have standard errors, CI not possible 
```

I can add confidence intervals by using `lines` and manually adding them or by setting the std.chaz variable to std.err, so this does have a workaround. Please let me know if this is not the correct workflow.

**Comment by therneau** [comment]
This has been restored.  However, a lot of work remains to be done for standard errors:  they are not present for the cumulative hazard in a multi-state model,  nor for cumulative hazard or survival in a multi-state coxph model.  We're working on it - slowly.
