### ISSUE TITLE
test for difference in survival probability between strata

### ISSUE THREAD

**Issue by MichelMoser** [therneau/survival#170]
Hello, 

Is there a statistical test (maybe implemented in survival package) which allows me to statically test for differences between survival probabilities at any given time between two strata?

I know that summary(fit, times = time) shows me so it should be possible to **compute a p-value** to the different estimates as well? 

Or maybe i miss some statistical complexity when computing survival probability estimates =) ? 

For example: 
```
vet <- veteran %>% filter(celltype %in% c("large", "smallcell"))
summary(survfit(Surv(time, status) ~ celltype, data = vet), times = 20)
```
 
```
Call: survfit(formula = Surv(time, status) ~ celltype, data = vet)

                celltype=smallcell 
        time       n.risk      n.event     survival      std.err lower 95% CI upper 95% CI 
     20.0000      37.0000      13.0000       0.7292       0.0641       0.6137       0.8664 

                celltype=large 
        time       n.risk      n.event     survival      std.err lower 95% CI upper 95% CI 
     20.0000      24.0000       3.0000       0.8889       0.0605       0.7779       1.0000 
```

I see that the confidence intervals overlap, so it would be nice to be able to test for difference in survival probability at time 20. 
How would i do that? 

Thank you, 
Michel

**Comment by therneau** [comment]
Since the two groups (strata) are disjoint subjects, the estimates are independent.  Variance( s1 - s2) = variance(s1) + variance(s2).

In your example below (.8889 - .7292)/ sqrt(.0641^2 + .0605^2)  =  1.8, p of about .7

**Comment by MichelMoser** [comment]
Of course, thank you! I assume you meant 0.07 =)
