### ISSUE TITLE
Is there any utility in producing the Nagelkerke Rsq when the 'newdata' parameter is specified in the royston function?

### ISSUE THREAD

**Issue by Feakster** [therneau/survival#171]
Looking at the code internals for the `royston()` function in version 3.2.13 of the _survival_ package, it appears that for a given Cox-PH model object (`fit`) the Nagelkerke _R<sup>2</sup>_ is defined as follows:

```r
logtest <- -2 * (fit$loglik[1] - fit$loglik[2])
R.n <- 1 - exp(-logtest/fit$n)
```
Given this is the case, is there any use in producing the Nagelkerke _R<sup>2</sup>_ in the `royston()` function output when the `newdata` parameter has been defined by the user? This could lead to confusion as this pseudo-_R<sup>2</sup>_ value is entirely dependent on the model fit to the derivation data, (i.e. makes no use of `newdata`):

```r
### Packages ###
library(survival)

### Lung Data Management ###
lung <- lung
lung[['inst']] <- NULL
lung[] <- lapply(lung, as.integer)
lung[['status']] <- lung[['status']] - 1L
lung[['sex']] <- factor(lung[['sex']], 1:2, c('Male', 'Female'))
lung[['ph.ecog']] <- factor(lung[['ph.ecog']], 0:4, c('Asmp', 'Symp', rep('Bed', 3)))
lung <- lung[order(lung[['time']]), ]
lung <- na.omit(lung)
rownames(lung) <- NULL

### New Random Lung Data ###
n <- nrow(lung)
lung2 <- lapply(lung, function(x) sample(unique(x), n, T)); rm(n)
lung2 <- as.data.frame(lung2)
lung2 <- lung2[order(lung2[['time']]), ]
rownames(lung2) <- NULL

### Cox-PH Model ###
reg_cox <- coxph(
  formula = Surv(time, status) ~ .,
  data = lung
)

### Nagelkerke Rsq ###
royston(reg_cox)[['R.N']]
# [1] 0.1517208368
royston(reg_cox, newdata = lung2)[['R.N']]
# [1] 0.1517208368
```

**Comment by therneau** [comment]
You are correct, there is no sensible Nagelkirke value for newdata.   I've change the function, and it now omits that value when newdata is present.

**Comment by Feakster** [comment]
Thank you.
