### ISSUE TITLE
clogit don't have an access to the public method from survival namespace

### ISSUE THREAD

**Issue by gogonzo** [therneau/survival#174]
Hi,
I've experienced a strange issue, calling `clogit` in my package. I found out that  `@importFrom survival clogit` is not enough and I need `@importFrom survival clogit coxph strata`. I don't understand why `survival::clogit` can't have the access to the functions from the package namespace.
Problem can be presented using this example
```r
data <- data.frame(
  RSP = c(1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1), 
  ARM = factor(
    c(2L, 2L, 2L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L), 
    labels = c("B: Placebo", "A: Drug X")), 
  AGE = c(34L, 29L,28L, 31L, 27L, 43L, 43L, 39L, 37L, 39L, 41L, 42L, 46L, 34L, 36L,21L, 38L, 41L, 29L, 34L), 
  STRATA1 = c(3L, 1L, 3L, 3L, 1L, 2L, 2L, 3L, 3L, 3L, 1L, 2L, 1L, 2L, 1L, 2L, 3L, 3L, 1L, 2L)
)


survival::clogit(
  formula = RSP ~ ARM + AGE + strata(STRATA1),
  data = data
)
# could not find function "strata"

survival::clogit(
  formula = RSP ~ ARM + AGE + survival::strata(STRATA1),
  data = data
)
# could not find function "coxph"
```

I guess this might be related to evaluating call in the parent.frame, which would be a `.GlobalEnv`. This means that calling `survival::clogit` excludes this evaluation from the `survival` functions and also from it's imports. Could you explain if it's expected and long term decision?

https://github.com/therneau/survival/blob/b45e1d20d2ac286424cf68f86a426b55bbb057f2/R/clogit.R#L51

-----
Digging deeper

```r
library(survival)
coxph <- function(...) stop("I'm not from the survival but still I'm teasing you")

data <- data.frame(
  RSP = c(1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1), 
  ARM = factor(
    c(2L, 2L, 2L, 1L, 1L, 2L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 2L, 1L), 
    labels = c("B: Placebo", "A: Drug X")), 
  AGE = c(34L, 29L,28L, 31L, 27L, 43L, 43L, 39L, 37L, 39L, 41L, 42L, 46L, 34L, 36L,21L, 38L, 41L, 29L, 34L), 
  STRATA1 = c(3L, 1L, 3L, 3L, 1L, 2L, 2L, 3L, 3L, 3L, 1L, 2L, 1L, 2L, 1L, 2L, 3L, 3L, 1L, 2L)
)


clogit(
  formula = RSP ~ ARM + AGE + strata(STRATA1),
  data = data
)
# error: I'm not from the survival but still I'm teasing you 
```

**Comment by therneau** [comment]
This is a question for r-help.   The working of import are at a level way above the package.   I suspect that if you import a function you have to import all the ones it calls?    But that's only a guess.   "How imports work" is a question for CRAN or R core level.
