### ISSUE TITLE
Seeking confirmation of survfit.print confidence intervals

### ISSUE THREAD

**Issue by kputschko** [therneau/survival#175]
In this post from 2006, I see that someone suggests that the confidence intervals provided by `survfit.print` are Brookmeyer Crowley confidence intervals.  However, I can't find any other suggestions since then that these confidence intervals are indeed BC intervals.  Can you confirm that this is accurate?

- https://stat.ethz.ch/pipermail/r-help/2006-February/088395.html

**Comment by therneau** [comment]
The survfit algorithm:  draw 95% pointwise confidence bands on the curve.   Now draw a horizontal line at y= .5.   Where the line intersects the curve is the median, where it intersects the confidence bands are the CI for the median.   A rather obvious approach.
  To answer your question, I don't know if Brookmeyer had the same idea and published it.   I suggest reading their paper  -- I simply don't have time to do so in the next few weeks.
