### ISSUE TITLE
Potential weighting issue with survreg?

### ISSUE THREAD

**Issue by jgaf151** [therneau/survival#176]
Hello,

We have been working on fitting survival models with Weibull distributions using the survreg function. We have a dataset of 8250 respondents that are weighted to be representative of a ~1.05 million population. We noticed that when we fit the model using the "weights" parameter, all of our covariates are significant at the <0.001 level, the SEs are very small, and our z values are high. Considering this, the extracted ranges between upper and lower CIs are small. We were surprised that all covariates were significant and the small variation in CIs. On further QCing, we ran the same model in STATA, and although the coefficients were basically the same, the significance, SE, and t values were wildly different. Note that running the models without weights in both programs yielded basically the same result. Running a coxph() weighted model produced similar results in R and STATA.  

I attempted to look through both the survreg() function and coxph() to see how the weight parameter is handled, but my knowledge is limited in this area. Any help would be appreciated. We might be missing extra parameters or controls that need to be applied.

Here is a example model just using one covariate:

```
> weib_res <- survreg(Surv(SURV_TIME_YRS, TXN_TYP_CD) ~ 
+                       Cluster,
+                     data = data_weib, 
+                     weights =  FINALWGT,
+                     dist = "weibull")
> weib_fit <- survreg(Surv(SURV_TIME_YRS, TXN_TYP_CD) ~ 
+                       Cluster,
+                     data = data_weib, 
+                     weights =  FINALWGT,
+                     dist = "weibull")
> summary(weib_fit)

Call:
survreg(formula = Surv(SURV_TIME_YRS, TXN_TYP_CD) ~ Cluster, 
    data = data_weib, weights = FINALWGT, dist = "weibull")
                    Value Std. Error     z                   p
(Intercept)       2.58218    0.00458 563.4 <0.0000000000000002
ClusterCluster 1 -0.23334    0.00571 -40.9 <0.0000000000000002
ClusterCluster 2 -0.13186    0.00592 -22.3 <0.0000000000000002
ClusterCluster 4 -0.20020    0.00549 -36.5 <0.0000000000000002
ClusterCluster 5 -0.53022    0.00591 -89.7 <0.0000000000000002
Log(scale)       -0.19665    0.00219 -89.8 <0.0000000000000002

Scale= 0.821 

Weibull distribution
Loglik(model)= -683471   Loglik(intercept only)= -687465.5
        Chisq= 7989.15 on 4 degrees of freedom, p= 0 
Number of Newton-Raphson Iterations: 7 
n= 8250

#Transform to HRs 
SurvRegCensCov::ConvertWeibull(weib_fit, conf.level = .95)$HR
                       HR       LB       UB
ClusterCluster 1 1.328501 1.310596 1.346651
ClusterCluster 2 1.174113 1.157653 1.190808
ClusterCluster 4 1.275972 1.259412 1.292749
ClusterCluster 5 1.906839 1.880467 1.933581
```

Same model in STATA:
![image](https://user-images.githubusercontent.com/16786565/150148665-606bfbb4-6a10-4f9e-a174-1f4e060ab046.png)

Best regards,

**Comment by therneau** [comment]
You have to specify the robust =TRUE (or cluster or id options).  I have added a paragraph to the help page to clarify this. 
 
Weights come in two flavors.  A replication weight of '2' means that there are two identical observations, which have been combined into one row to save space.  When computer memory was much smaller, they were very common -- just knowing about this dates me.  (I started computing on an IBM 1130, 8K of memory, punch cards).   For this you want the default variance.   For sampling weights, now the common case, you want the survey sampling style variance specified by robust.
