### ISSUE TITLE
Censored Data Documentation

### ISSUE THREAD

**Issue by DarioS** [therneau/survival#181]
> Interval censored data can be represented in two ways. For the first use type = "interval" and the codes shown above. In that usage the value of the time2 argument is ignored unless event=3. The second approach is to think of each observation as a time interval with (-infinity, t) for left censored, (t, infinity) for right censored, (t,t) for exact and (t1, t2) for an interval. This is the approach used for type = interval2. Infinite values can be represented either by actual infinity (Inf) or NA. The second form has proven to be the more useful one.

Can the difference between these two modes be more explicit? It sounds to me like, in the first approach, `time2` is ignored unless `event = 3`. But, the second approach seems identical because t2 is only mentioned when there is an interval. Could an example in Examples section make this difference I can't see more concrete?

Also, when I use `heart` as in the example `Surv(heart$start, heart$stop, heart$event)`, it's not exactly clear from `?heart` what do the three columns practically mean. Based on there being three columns, this means that it's a counting process data. My understanding is that the first column is time of enrollment (1 means 1 unit of time after the study began the person enrolled), the second is time of last follow-up, and the event is a binary indicator of whether there was an event at `time2` or not. I wonder if for "Entry and exit time and status for this interval of time" that instead "Entry and exit time and status  **at the end of** this interval of time" would be more what's intended? I hope this provides a beginner's perspective on the help pages that you might not get to see often.

**Comment by therneau** [comment]
I've read the help file and made a small improvement (I think).  I  don't see the phrase "entry and exit time and status", but perhaps I already changed that.
