### ISSUE TITLE
veteran data: Data/Documentation descrepancy

### ISSUE THREAD

**Issue by adibender** [therneau/survival#19]
Note that `prior` variable takes values `0` and `10`
```r
library(survival)
head(veteran)
  trt celltype time status karno diagtime age prior
1   1 squamous   72      1    60        7  69     0
2   1 squamous  411      1    70        5  64    10
3   1 squamous  228      1    60        3  38     0
4   1 squamous  126      1    60        9  63    10
5   1 squamous  118      1    70       11  65    10
6   1 squamous   10      1    20        5  49     0
```

whereas  `?veteran` claims that `prior` schould be coded:
"prior:	prior therapy 0=no, 1=yes"

**Comment by therneau** [comment]
Thanks for the note.  I have fixed the documentation.  The variable is 0 or 10 in 
Kalbfleisch and Prentice book.  I have no idea why they coded it that way.

Terry T.
