### ISSUE TITLE
brier Function Not Exported

### ISSUE THREAD

**Issue by DarioS** [therneau/survival#191]
I notice `brier` function but it is not exported nor documented. Will it be released soon? I am looking for integrated Brier score. But, perhaps I should not be ... [The Brier Score Does Not Evaluate the Clinical Utility of Diagnostic Tests or Prediction Models](https://diagnprognres.biomedcentral.com/articles/10.1186/s41512-017-0020-3).

**Comment by therneau** [comment]
Sharp eyes!  I have to write the test suite for it and validate, then the help file, then add it it.    I intended this to be done a while ago.

**Comment by therneau** [comment]
The brier function is now complete and tested, along with a new vignette.
