### ISSUE TITLE
Survival probability is not monotonically decreased across time

### ISSUE THREAD

**Issue by L-1996-G** [therneau/survival#193]
Hi, 
I have panel-structured data (e.g. I observe one ID several time). I have built cox PH model with time-varying covariates (`coxph(Surv(time1, time2, event)~., data=data)`) and then make prediction with following code: `predict(fit, data, type = 'survival')`.  Unfortunately, predicted survival probability is not decreased over time (e.g. For same ID, predicted survival probability for time2=100 is 0.995, while for time2=103 predicted survival probability is equal to 0.996). Conceptually survival probability must be monotonically decreasing. 

what is problem and how to achieve monotony?

Thanks

**Comment by therneau** [comment]
You have a (time1, time2) data set.  The resulting probability is for survival from time1 to time2, not for survival from 0 to time 2.
Or at least that is my best guess, since you showed neither data nor code.
