### ISSUE TITLE
Performance boost in order() calls

### ISSUE THREAD

**Issue by piotrp88** [therneau/survival#2]
I've just seen a performance improvement on coxph() after imposing the usage of the radix method for every `order()` and `sort()` function used in the survival package:
`order(..., method="radix")` and `sort(..., method="radix")`.

**Comment by therneau** [comment]
How big a sample size, and how big a boost?  Were there strata?

In the development version of R the default method has changed to "auto", which chooses 
radix or shell according to built in rules about which will be best.  Thus I think this 
improvement will happen automatically.

 From the manual page:
The "auto" method selects "radix" for short (less than 2^31 elements) numeric vectors, 
integer vectors, logical vectors and factors; otherwise, "shell".


Terry T.

**Comment by piotrp88** [comment]
Boost is exponential and gets bigger as the sample size grows. I had no strata but time-dependent covariates and >2 million rows. I issued this call:
coxph(data=mydata, Surv(start, stop, event) ~ cluster(id) + cov1 + cov2)
where cov1 is a factor with two levels and cov2 is a dicotomous (integer) covariate.
I edited all the order() and sort() involved in coxph.R and agreg.fit.R and tested on a OS X Mavericks environment with R 3.3.2 and Intel i7@2.8GHz.
The speed gain is significant, I don't remember exactly the numerical timings but on the various order() and sort() calls saved some seconds over a 41 overall seconds execution. With bigger datasets it gets much better.

Also, I would like to suggest another little improvement for agreg.fit.R, changing this:
```
agreg.fit <- function(x, y, strata, offset, init, control,
                        weights, method, rownames)
    {
    n <- nrow(y)
    nvar <- ncol(x)
    start <- y[,1]
    stopp <- y[,2]
    event <- y[,3]
    if (all(event==0)) stop("Can't fit a Cox model with 0 failures")

    # Sort the data (or rather, get a list of sorted indices)
    #  For both stop and start times, the indices go from last to first
    if (length(strata)==0) {
        sort.end  <- order(-stopp) -1L #indices start at 0 for C code
        sort.start<- order(-start) -1L
        newstrat  <- n
    }
...
```
to this:
```
agreg.fit <- function(x, y, strata, offset, init, control,
                        weights, method, rownames)
    {
    n <- nrow(y)
    nvar <- ncol(x)
    event <- y[,3]
    if (all(event==0)) stop("Can't fit a Cox model with 0 failures")

    # Sort the data (or rather, get a list of sorted indices)
    #  For both stop and start times, the indices go from last to first
    if (length(strata)==0) {
        sort.end  <- order(-y[,2]) -1L #indices start at 0 for C code
        sort.start<- order(-y[,1]) -1L
        newstrat  <- n
    }
...
```
`start` and `stopp` aren't used in other parts of the function and can be omitted; the respective values, `y[,1]` and `y[,2]`, can be moved in place of `start` and `stopp`. Probably this applies to other fitters, but I haven't checked since I worked only on this script.

**Comment by therneau** [comment]
Done.
