### ISSUE TITLE
Per-sample C-index

### ISSUE THREAD

**Issue by DarioS** [therneau/survival#207]
I was reading the documentation and thought I understood how to calculate a sample-specific C-index. I would like to identify the samples with inaccurate risk predictions and then check their clinical data for commonalities (e.g. similar treatment history).

```r
> head(actualOutcomes)
[1] 11.46+  4.90   3.18+  5.81   2.36   3.99
> predictedOutcomes <- -predictedOutcomes # Output of predict with type = "risk".
> head(predictedOutcomes)
Sample 32 Sample 36 Sample 48 Sample 28  Sample 9 Sample 24 
    -1.89     -0.35     -0.52     -0.39     -0.08    -33.95
> head(samples)
[1] Sample 32 Sample 36 Sample 48 Sample 28 Sample 9  Sample 24
50 Levels: Sample 1 Sample 2 ... Sample 50
> survival::concordance(actualOutcomes ~ predictedOutcomes + strata(samples), keepstrata = lnf)$concordance
[1] NaN
```

So, instead of one number, I want a vector as long as number of samples. Can this be done easily using the survival package?

**Comment by therneau** [comment]
I have never considered the per-subject contribution to the C-index as a 'statistic' of interest.    I'm not aware of any work that uses "impact on the C statistic" as a measure of goodness-of-fit for an observation, but such a literature could certainly exist.  

You can get a good approximation to this using the dfbeta argument, i.e.,
```{r}
cfit <- coxph(Surv(time, status) ~ rx + age + extent + nodes, colon,  subset=(etype==1))
temp <- concordance(cfit, dfbeta=TRUE)
hist(temp$dfbeta)
```
The larger negative values are subjects who are not well predicted, i.e., they make the concordance smaller.

A strata is certainly not the way to do it: observations within each stratum are only compared to others in the same stratum.
