### ISSUE TITLE
MSc project related

### ISSUE THREAD

**Issue by Whynnie** [therneau/survival#209]
Good day, I'm working on my MSc project and this is my topic is Deep Semi-supervised Multitask Learning Model for Survival Analysis. Please, I need your professional advice and guidance.

**Comment by Whynnie** [comment]
Please, I don't seem to understand the arrangement of these folders. Could you arrange them in order for me, I'm perplexed.

**Comment by therneau** [comment]
This is a list for discussing issues with the package.   It is not a tutorial service.
