### ISSUE TITLE
Using start.time with survfit.formula

### ISSUE THREAD

**Issue by noambard** [therneau/survival#21]
My apologies if I misunderstood the code, but it seems to me there is a problem.

survfit.formula calls survfitCI
when a start.time parameter is passed, lines 104 - 112 try and toss out those lines that have an end time that is earlier than the start.time.
But the code checks "toss <- which(Y[,ncol(Y)] <= start.time)", when the actual end times are in column ncol(Y)-1. As it is, it checks the status column and tosses out wrong lines.

**Comment by therneau** [comment]
I think you are right.

**Comment by therneau** [comment]
Now repaired, and a test case added to tests/testci2.R
