### ISSUE TITLE
Small Typo Report in `survfit.formula()` Documentation

### ISSUE THREAD

**Issue by ddsjoberg** [therneau/survival#210]
- [ ] The description of the `survfit.formula(etype=)` argument includes a typo of "depricated" instead of "deprecated". 
- [ ] The description of the `survfit.formula(cluster=)` argument includes a typo of "infinitesmal" instead of "infinitesimal". 

Thank you for all your work maintaining this essential package! 🥇

**Comment by therneau** [comment]
Now fixed.   (There were even more instances of depricated).
