### ISSUE TITLE
Clarification to `coxph` documentation for `robust` and `weights` arguments? 

### ISSUE THREAD

**Issue by R-Walmsley** [therneau/survival#218]
I recently had [a question on Cross Validated](https://stats.stackexchange.com/questions/595082/how-do-the-defaults-for-the-weights-argument-and-the-robust-argument-work-in) on the `weights` and `robust` arguments to `coxph`  (unfortunately closed as off-topic...). I found the behaviour difficult to work out from the documentation.

Specifically, the documentation for robust says:
 
> should a robust variance be computed. The default is TRUE if: there is a cluster argument, there are case weights that are not 0 or 1, or there are id values with more than one event.

The section on weights says:

> Case weights are treated as replication weights, i.e., a case weight of 2 is equivalent to having 2 copies of that subject's observation. When computers were much smaller grouping like subjects together was a common trick to used to conserve memory. Setting all weights to 2 for instance will give the same coefficient estimate but halve the variance. When the Efron approximation for ties (default) is employed replication of the data will not give exactly the same coefficients as the weights option, and in this case the weighted fit is arguably the correct one.

> When the model includes a cluster term or the robust=TRUE option the computed variance treats any weights as sampling weights; setting all weights to 2 will in this case give the same variance as weights of 1.

I think I now understand the behaviour (integer weights are treated as case weights, but non-integer weights trigger robust variance?), but I wonder if the documentation around weights might be clarified?

**Comment by therneau** [comment]
Suggest a better wording and I'll consider it.

**Comment by R-Walmsley** [comment]
Apologies for the slow response - I have left the job in which I came across this issue, and no longer have access to the script in which I documented the function's behaviour. I will look into whether I can recreate it and amend the documentation appropriately.
