### ISSUE TITLE
Create github page with {usethis} package

### ISSUE THREAD

**Issue by brunomioto** [therneau/survival#219]
You can just run [`usethis::use_pkgdown_github_pages()`](https://usethis.r-lib.org/reference/use_pkgdown.html)

**Comment by therneau** [comment]
I have no idea what you are talking about.   What is the overall point of this post?

**Comment by brunomioto** [comment]
The idea is create a auto-updating website for this package. It will render a website every time you update your package (take a loot at https://ggplot2.tidyverse.org/index.html)
It makes it easier to find functions (that was my problem) and it can be easier for new users

**Comment by therneau** [comment]
I have no interest in expanding the scope of the github page.    First, as noted on the main page, this is a courtesy copy of the real repository, which is in mercurial, on a Mayo internal server.   Second, as a recommended package, this cannot depend on anything outside of  R base + recommended.   (So all the vignettes are in Sweave, even though I personally prefer knitr.)
