### ISSUE TITLE
tail() broken for Surv objects

### ISSUE THREAD

**Issue by lawremi** [therneau/survival#22]
```
> cens <- sample(0:1, 100, replace=TRUE)
> time <- rnorm(100)
> s <- Surv(time, cens)
> tail(s)
Error in unclass(x)[i, , drop = FALSE] : subscript out of bounds
```
The issue is that `length(s)` returns the length of the underlying matrix, so it's twice what it probably should be (given how `print.Surv()` and `[.Surv()` work).
```
> length(s)
[1] 200
```
The other option is of course a `tail.Surv()`.

**Comment by therneau** [comment]
I have now added tail, unique, and duplicated methods for Surv objects.  Good catch.
