### ISSUE TITLE
Partial argument matching

### ISSUE THREAD

**Issue by chjackson** [therneau/survival#222]
I had an issue report about the use of partial argument matching in some of flexsurv's code (e.g. `seq(length=` instead of `seq(length.out=` or `seq_len`) so I ran flexsurv's tests with these options set: 

```
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE
)
```
which then returned warnings due to the following use of partial argument matching in `survreg` (that was being called in some of flexsurv's code) `fit$coef` in line 269 of [survreg.R](https://github.com/therneau/survival/blob/master/R/survreg.R).    You may or may not be bothered about this!  Though I also noticed a typo in the next line 270, `fit$coeffients`, which you may be more bothered by.

**Comment by therneau** [comment]
You are correct.   Now fixed in my master copy.   I have 2 more errors to look at, then I'll push it up to github.
