### ISSUE TITLE
survival::survfit segfaults

### ISSUE THREAD

**Issue by alonme** [therneau/survival#225]
Hey,

I am not sure what is the exact change that caused this, but after a major change in my model i started encountering segfaults in my production environment (debian linux) 

Because it was big change (and doesn't reproduce on my local machine) i am not sure what was the exact cause, and am looking for clues for what can be the case

Exampel Error:
```
 *** caught segfault ***
address 0x557a79357a70, cause 'memory not mapped'
```

the relevant part of the traceback

```
Traceback:
 1: survfitKM(X, newY, casewt, stype = stype, ctype = ctype, id = id,     cluster = cluster, robust = robust, ...)
 2: survfit.formula(x ~ 1, conf.type = "plain", start.time = min_time,     timefix = F, id = id, subset = subset)
 3: survival::survfit(x ~ 1, conf.type = "plain", start.time = min_time,     timefix = F, id = id, subset = subset)
```

This happens both in version `3.3-1` (which i used before the upgrade) and in the latest `3.5-5`.

I'll be happy to provide any more useful data, 

Thanks

Some more info

```
/app# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by therneau** [comment]
I need a data set that demonstrates this error.   A segfault is serious, but I can't reproduce it without an example
