### ISSUE TITLE
Functionality for Fast Univariate Tests of Tabular Input

### ISSUE THREAD

**Issue by DarioS** [therneau/survival#227]
Similar to `rowFtests` and `colFtests` in [genefilter](http://bioconductor.org/packages/release/bioc/html/genefilter.html), could [survival](https://cran.r-project.org/web/packages/survival/index.html) have functionality which does fast computation in C or C++ over either the rows or columns of tabular data, to allow univariate feature selection of variables associated with survival? `colCoxTests`?

**Comment by therneau** [comment]
Could you be a little clearer about what exactly you want?   (Most of the serious computation in the survival package is already in C, by the way).   

I make a guess about what you want, which is to test for the significance of gene 'X' on survival, say after adjusting for age?   There is a fast approximation for this:  the sum of  x* marginale-residuals is the numerator of the score test for the addition of 'x' to the regression, so you can very easily rank the variables.   But variance is a bit harder.

If I am correct, I'm not sure this belongs in the survival package; it might more logically be placed into genefilter.

**Comment by DarioS** [comment]
Thanks for the suggestion. Yes, fast computation on thousands of variables, one-at-a-time. I agree that it might be better suited to genefilter or a similar package and I will discuss it with the package developer there.
