### ISSUE TITLE
broken Rd markup

### ISSUE THREAD

**Issue by bastistician** [therneau/survival#229]
Checking **survival** under `_R_CHECK_RD_CHECKRD_MINLEVEL_=-Inf` in R-devel highlighted two issues with Rd markup:

https://github.com/therneau/survival/blob/e8de7b732daa9a82c1ceaad93fd68ee7545c7736/man/dsurvreg.Rd#L78
gives `F(t)1 - exp((-lambda t)^p)` in text-mode help: I suppose `F(t)}{` was meant to be `F(t)=`.

https://github.com/therneau/survival/blob/e8de7b732daa9a82c1ceaad93fd68ee7545c7736/man/survfit.formula.Rd#L162
lacks a backslash escape for the `\code` macro.

**Comment by therneau** [comment]
Now fixed in my copy; thanks.
