### ISSUE TITLE
predict.coxph() gives error when newdata-arg is given

### ISSUE THREAD

**Issue by strengejacke** [therneau/survival#23]
When I call the predict funtion with newdata-argument and a different type-value that default, I get an error:

```
library(survival)
library(dplyr)

test1 <- data.frame(time=c(4,3,1,1,2,2,3), 
              status=c(1,1,1,0,1,1,0), 
              x=c(0,2,1,1,1,0,0), 
              sex=c(0,0,0,0,1,1,1)) 

# Fit a stratified model 
fit <- coxph(Surv(time, status) ~ x + strata(sex), test1) 
dat <- dplyr::distinct(expand.grid(x = test1$x, sex = test1$sex))

predict(fit, newdata = dat, type = "expected")
#> Error in Surv(time, status) : object 'status' not found

fit2 <- lm(time ~ x + sex, test1) 
predict(fit2, newdata = dat)
```

w/o newdata, it works:

```
predict(fit, type = "expected")
#>         1         2         3         4         5         6         7 
#> 1.2631435 1.3094142 0.2137211 0.2137211 0.9537292 0.4275460 0.6187248 
```

**Comment by therneau** [comment]
Predictions of type=expected also need the follow-up time for the new subjects.  (If someone is followed for 1 day I wouldn't expect a death, if followed for 150 years I'm pretty sure of it.)   So in this case predict has to construct both the left and right sides of the formula - note that it is looking for "status" and can't find it.  I've added material to the manual page.

**Comment by strengejacke** [comment]
Ok, thanks! So, "lp" and "risk" are the only options for predictions on `newdata`, w/o needing a new survival-response?

May I ask two follow-up-questions: How to correctly compute CI for risk scores from linear predictors? This is my current approach:

```
prdat <- stats::predict(model, newdata = fitfram, type = "lp", se.fit = T, ...)

predicted <- exp(prdat$fit)
# calculate CI
conf.low <- exp(prdat$fit - stats::qnorm(.975) * prdat$se.fit)
conf.high <- exp(prdat$fit + stats::qnorm(.975) * prdat$se.fit)
```


And 2nd: What are the predicted values called? Predicted risk scores?
