### ISSUE TITLE
Vignette: Minor corrections

### ISSUE THREAD

**Issue by LGraz** [therneau/survival#230]
Thanks for the package <3 

In the [vignette](https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf) Equation 2.1 has a typo and could be improved. The current one is:
$\hat{S}_{K M}(t)=\prod_{s<t} \frac{\bar{Y}(t s)-d(s)}{\bar{Y}(s)}$

this should be corrected to 
$$\hat{S}_{K M}(t)=\prod_{s<t} \frac{\bar{Y}(s)-d(s)}{\bar{Y}(s)}$$

but now one should still explain what $s$ means (only valid survival times)

I would recommend:  
$$\hat{S}_{K M}(t)=\prod_{k: t_k<t} \frac{\bar{Y}(t_k)-d(t_k)}{\bar{Y}(t_k)}$$  
with $t_k$ being the k-th time when an event happened.

**Comment by therneau** [comment]
I've fixed this in my copy, thanks.
