### ISSUE TITLE
Zero deemed invalid lower bound for interval censored data in survreg with lognormal

### ISSUE THREAD

**Issue by chjackson** [therneau/survival#234]
`survreg` produces `"Invalid survival times for this distribution"`, when interval-censored data for the lognormal have a lower bound of zero.
```{r}
emin <- c(0, 1:10)
emax <- emin + 1
survreg(Surv(emin, emax, type="interval2") ~ 1, dist="lognormal")
```
I agree zero is invalid for a log-normally distributed event time, but I think it should be valid as a lower bound with interval censoring, or have I missed something?  This also happens for the log logistic - I haven't tested for others.

**Comment by therneau** [comment]
Now fixed.
