### ISSUE TITLE
Feature request: Firth correction

### ISSUE THREAD

**Issue by carbocation** [therneau/survival#236]
I'm wondering if adding optional Firth correction might be possible. I ask because, although there is a coxphf package, that package does not currently support multistate models or competing hazards models like this package does. For completeness, I have also opened a parallel inquiry over on the [coxphf issues](https://github.com/georgheinze/coxphf/issues/17) to see if there is a way to instead add multistate or competing hazards models to that package. Ultimately, I think it would be helpful if there were an R package that could both handle competing hazards and perform Firth correction.

**Comment by therneau** [comment]
The Firth 'correction' is a penalized model, and in my opinion it more fits as an option in coxme.  That is, it is simply  a different penalty than a Gaussian.    Updating coxme to handle multi state models is on my to do list (but unfortunately has been there for a long time.)
