### ISSUE TITLE
In predict.coxph, how is se.fit calculated?

### ISSUE THREAD

**Issue by StephenBarron** [therneau/survival#24]
Hi there, 

I'm using the predict.coxph function to use a coxph object to calculate linear predictors for new set of observations. I can get standard errors for these linear predictors by specifying se.fit=TRUE. I'd like to know how these standard are errors calculated?

Many thanks
Stephen

**Comment by graemeleehickey** [comment]
SEs for the fixed effects are calculated from `vcov()` and SEs for the baseline hazard are available from `coxph.detail()`.

**Comment by therneau** [comment]
Are you asking an R question or a math question?   The math answer is that any linear combination of the coefficients  z' beta  has a variance of z' var(beta) z, where z is the vector of constants.  Standard stuff.

**Comment by StephenBarron** [comment]
Thanks for getting back to me. So se.fit is calculated as the square root [variance of the linear combination of the regression coefficients and data values]?
