### ISSUE TITLE
Standard errors for new data exhibit unexpected behavior

### ISSUE THREAD

**Issue by juliannaharwood** [therneau/survival#255]
1. When I use a fitted model to predict survival for duplicate rows of new data, the survival prediction stays the same, but the `se.fit` varies for each observation:
```
survival <- predict(model, sample, type = "survival", se.fit = TRUE)
survival$fit
[1] 0.9787033 0.9787033 0.9787033
survival$se.fit
[1] 6.449212e-06 4.529473e-03 5.883216e-06
```
2. When I used a fitted model that was trained on data of size `m x n` to predict new data of size `m2 x n2`, if `m2 > m` then the `se.fit` field of the prediction object is null after `m` values (meaning there are only `m` standard errors ever returned for new data).

I'm wondering if this has something to do with this line in the source code of `predict.coxph`: 
```
se[indx2] <- sqrt(v2-v1)* risk[indx2]
```
It seems that the `risk` which is based off of the training data (and thus the length of the training data) is being used to calculate the standard error, which will limit it to the length of the training data.

Thanks in advance!

**Comment by therneau** [comment]
You have given me nothing to work with.  What is "model", what is "sample"?    How could I reproduce your issue?

**Comment by therneau** [comment]
Now repaired.   Finishing up a new test file.
