### ISSUE TITLE
Veterans Administration Data wrong hazard ratio reported

### ISSUE THREAD

**Issue by aeleuteri** [therneau/survival#265]
Dear Professor,
There seems to be an issue with the reported hazard ratio (and interpretation) of the Veterans data in the timedep vignette:

https://github.com/therneau/survival/blob/37792dbd5f5d28370c2f16526cff514466e362cb/vignettes/timedep.Rnw#L879

The coefficient from the fit is -0.033771, which means that the hazard ratio for the karno quantiles is exp(-0.033771*(75-40))=0.31, i.e. the Karnofsky score is overall protective; and the graph shows a large protective effect at the start, which wanes later. These considerations reflect section 6.3 in the textbook Modeling Survival Data.

Regards
Antonio

**Comment by therneau** [comment]
Someone at the first quartile  of Karnofsky score (40) is at much higher risk than someone at the third quartile (75).    Remember that a Karnofsky of 100 is good, 0 is dead.   The sentence is correct as stated.

**Comment by aeleuteri** [comment]
Thanks for the reply. 
I am missing something then, I think. Assuming that -0.05 is meant to approximate the (almost) -0.06 at time 0 in figure 1 from the spline smoothing, then we get that for subjects with Karnofsky 40, the hazard is exp(-0.05*40)=0.14, and for subjects with Karnofsky 75, it's exp(-0.05*75)=0.024; so higher Karnofsky, lower risk (as intuition suggests). So why the statement that "Early on it has a large negative effect"?

**Comment by therneau** [comment]
I am saying  that "abnormal Karnofsky is bad" and you that "high Karnofsky is good".

**Comment by aeleuteri** [comment]
Thank you! I was "lost in translation"; I am not a native English speaker, so I misinterpreted the meaning of "early on".
