### ISSUE TITLE
Cox model with percentage interpretation

### ISSUE THREAD

**Issue by LeaLe88** [therneau/survival#266]
Good morning,

I was wondering whether anyone could advice me on the following: I have a Cox model, which contains a variable with percentage (cell fractions). It makes it hard to interpret the HR in the model.

Can you advise me on how to deal with a variable with percentage in the model to make them easier to interpret?

Thank you & Best Regards!

**Comment by therneau** [comment]
This can only be answered in the context of a particular study.   In post remission monitoring of multiple myeloma, a change from 0 to 1%  presence of the malignant clone within the plasma cell population is a big red flag for "escape" from the treatment.  On the other hand a 10% change in white blood cell differential counts is not nearly so worrisome, e.g. a temporary shift in response to a head cold.    No very answer can be given without real consultation.   I've been in medical research for just over 40 years, and for any new project the first hour of consultation consists solely of me asking questions about the research.

**Comment by LeaLe88** [comment]
Thank you for your answer. Maybe my question was not clear. I meant more like if there is a way to transform percentage into a more interpretable variable in a Cox model with Hazard Ratio.
