### ISSUE TITLE
Dealing with variable with percentage in cox model 

### ISSUE THREAD

**Issue by LeaLe88** [therneau/survival#267]
Good morning,

I was wondering whether you could advice me on the following: I have a Cox survival model in R (function coxph), which ,among other variables (e.g. age, sex), contains a variable with percentage (cell fractions, e.g. 10% endothelial cells, 50% epithelial cells). Having a variable with a percentage makes it hard to interpret the Hazard Ratio (HR) in the model.

Do you know who how to deal with a variable with percentage in a model (particular in Cox models) to make them easier to interpret?

Please find an example below:

coxph(formula = Surv(PFI.t_5y, PFI.e_5y) ~ gender + age +
percentage_cell_fractions, data = combined, model = TRUE)

HR for percentage:  0.351382 (What does this mean??)
P value for percentage: 0.044

Comment: HR < 1 normally means reduction of hazard of dying (e.g. being male reduces the HR of dying). But in the case of percentage how do I interpret that?

**Comment by therneau** [comment]
It is like any other continuous variable, e.g., age.   Each 1 unit change in 'percentage'  decreases the risk to about 1/3.    To interpret that, you need to decide what two percentage values you want to compare  (just like age).   Suppose that .5 and .7 were of interest, then  the HR will be = .81.   The higher of the two has about 20% less risk.
