### ISSUE TITLE
clogit fails 2.41-3

### ISSUE THREAD

**Issue by JesseWhittington** [therneau/survival#27]
clogit fails in 2.41-3 but not in 2.41-2.

Example from the help menu for ?clogit
```{r}
library(survival)
clogit(case ~ spontaneous + induced + strata(stratum), data=infert)
```
*Error in fitter(X, Y, strats, offset, init, control, weights = weights, : object 'Ccoxmart2' not found*     

         
```{r}
sessionInfo()
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
  [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                    LC_TIME=English_Canada.1252

attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
  [1] survival_2.41-3

loaded via a namespace (and not attached):
  [1] compiler_3.4.1  Matrix_1.2-11   tools_3.4.1     splines_3.4.1   grid_3.4.1      lattice_0.20-35

**Comment by therneau** [comment]
This isn't a source code issue, try communicating with me outside of github.  Usually it results from a newer version of R and and older copy of the survival library.

**Comment by JesseWhittington** [comment]
Hi Terry,

Thanks for the update.  I am fine using the previous version of survival
until the versions of R and survival align.  Next time if I see an issue,
I'll email you off line first.  Thank-you for producing such a great
package.  Much appreciated,

Jesse
