### ISSUE TITLE
survreg does not converge 

### ISSUE THREAD

**Issue by tdhock** [therneau/survival#270]
related to #8 in which data are only open intervals in survreg.

I have observed some data sets with a few dozen points, where survreg does not converge, but I expected that it should, because my similar function, penaltyLearning::IntervalRegressionUnregularized, does converge.
Here is a figure that explains the issue.
![image](https://github.com/user-attachments/assets/1162288d-38dd-4e50-b909-708f0ac286cd)
Panels from left to right are different data sets.
Panels from top to bottom are different packages.
The top panels represent the result of my penaltyLearning package, which minimizes a squared hinge loss (similar to the gaussian negative log likelihood in survreg). We see that there is a model computed for all three data sets.
The bottom panels represent survreg, and we see that 
* it works fine for the middle data set (extra.id: 13), 
* for the right data set (extra.id: 120), there is a warning about convergence, but finite coefficients are still returned.
* for the left data set (extra.id: 0), there is a warning about convergence, and missing coefficients are returned.

I know this code worked at some point in the past (circa 2017 which is when #8 was filed?), which is why I am filing this issue. We should look at past R versions to see when this stopped working.

Code to reproduce, from https://github.com/tdhock/change-tutorial/blob/master/figure-regression-interactive-some-bug.R
```r
library(survival)
full.df <- structure(list(id = c(1L, 1L, 1L, 1L, 1L, 1L, 4L, 4L, 4L, 4L, 
4L, 4L, 6L, 6L, 6L, 6L, 6L, 6L, 8L, 8L, 8L, 8L, 8L, 8L, 10L, 
10L, 10L, 10L, 10L, 10L, 11L, 11L, 11L, 11L, 11L, 11L, 13L, 13L, 
13L, 13L, 13L, 13L, 120L, 120L, 120L, 120L, 120L, 120L), lo = c(0.195727051766757, 
-1.1087553605429, -1.00065642410924, -0.995123241844028, -Inf, 
-1.81065319423307, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -0.694428755856871, 
-2.4887060208859, -3.44756655828744, -3.03711252743929, -3.14523459850271, 
-0.892319064459033, -0.552651313503626, -Inf, -2.43732789951484, 
-1.24650632092422, -Inf, -Inf, -1.50791410241527, -2.24743277679978, 
-2.37206425088304, -3.83417364430955, -2.60448041546997, -1.44599430482559, 
-Inf, -0.456570392651195, -0.249593970642512, -Inf, 0.552800358347374, 
1.03693235764513, 0.366866754402124, -2.52677122267308, -2.48507949525124, 
-1.54283966348088, -1.59313273785538, -2.44940446306835, -0.513882229855861, 
-3.450873922835, -3.02209394810166, -3.97458092881313, -3.57901135468839, 
-2.1845818324618), hi = c(Inf, Inf, Inf, Inf, 2.06739808397873, 
Inf, 3.26518538624204, 1.13643272732406, 2.27284346410842, 1.38565083489553, 
0.492585941448176, 2.13713710441581, Inf, Inf, Inf, Inf, Inf, 
Inf, Inf, 0.937658965079102, Inf, Inf, 3.17164978103177, 3.0679625505633, 
Inf, Inf, Inf, Inf, Inf, Inf, 2.39473287695651, Inf, Inf, 0.730793396188341, 
Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, 
Inf), feature = c(-2.65456939094638, -2.42126427679538, -2.0705540906376, 
-2.41236133374335, -2.38707136376868, -2.50995205248869, -2.36922164775071, 
-2.39136308372706, -2.35954108440544, -2.52855213967643, -2.61717785427761, 
-2.32148054113571, -2.90042209374967, -2.81341071676004, -2.90042209374967, 
-2.7646205525906, -2.97592964625781, -2.3434070875143, -2.87790396885268, 
-2.92818004477678, -2.91781583734955, -3.04532040079498, -2.44619735876083, 
-2.36685302923454, -3.17008566069877, -2.7646205525906, -2.54465665419377, 
-3.12356564506388, -3.20645330486964, -2.39689577246529, -2.43836426623075, 
-2.17187107950722, -2.52267471748792, -2.59336839058434, -1.84434871178509, 
-1.9783687469636, -3.01613697015902, -3.0756635490299, -2.93034936935621, 
-2.94970009845407, -2.89011456307748, -2.87110297166178, -3.01593498087151, 
-3.01593498087151, -2.94694210938456, -2.71055333132033, -3.11226608980994, 
-2.68824757380603)), class = "data.frame", row.names = c(NA, 
-48L))
model.fun.list <- list(
  survreg=function(train.df){
    fit <- with(train.df, survreg(
      Surv(lo, hi, type="interval2") ~ feature,
      dist="gaussian"))
    coef(fit)
  },
  penaltyLearning=function(train.df){
    fit <- with(train.df, penaltyLearning::IntervalRegressionUnregularized(
      cbind(feature), cbind(lo,hi)))
    coef(fit)[,"0"]
  })
dot.df.list <- list()
coef.df.list <- list()
text.df.list <- list()
for(extra.id in c(0,13,120)){
  sub.df <- subset(full.df, id %in% c(1, 4, 6, 8, 10, 11, extra.id))
  for(pkg in names(model.fun.list)){
    model.fun <- model.fun.list[[pkg]]
    try.out <- tryCatch({
      weight.vec <- model.fun(sub.df)
    }, warning=function(w)w$message)
    weight.vec <- model.fun(sub.df)
    dot.df.list[[paste(extra.id, pkg)]] <- with(sub.df, data.frame(
      extra.id, pkg,
      rbind(
        data.frame(limit="lo", output=lo, feature),
        data.frame(limit="hi", output=hi, feature))))
    coef.df.list[[paste(extra.id, pkg)]] <- data.frame(
      extra.id, pkg,
      warn.text=if(is.character(try.out))try.out else "",
      intercept=weight.vec[["(Intercept)"]],
      slope=weight.vec[["feature"]])
  }
}
dot.df <- subset(do.call(rbind, dot.df.list), is.finite(output))
coef.df <- do.call(rbind, coef.df.list)
text.df <- do.call(rbind, text.df.list)
library(ggplot2)
ggplot()+
  theme_bw()+
  geom_abline(aes(
    slope=slope, intercept=intercept),
    data=coef.df)+
  facet_grid(pkg ~ extra.id, labeller=label_both)+
  geom_point(aes(
    feature, output, fill=limit),
    shape=21,
    data=dot.df)+
  geom_text(aes(
    -3.2, 3, label=sprintf(
      "slope=%.2f\nintercept=%.2f\n%s", slope, intercept, warn.text)),
    vjust=1,
    hjust=0,
    data=coef.df)
```

**Comment by therneau** [comment]
Thank you for providing an example.   There was another recently that caused survreg to fail convergence.    I'm up to my elbows at the moment, but have a start on updating the code to use a trust region approach.

**Comment by tdhock** [comment]
git bisect says the culprit for extra.id=0 data is https://github.com/therneau/survival/commit/ede711c5fa4ce819801d856582369ee5eea94fd6#diff-4f0d94965fe3e1440e71f9cb6d8e2bd412df4871c08f7a5f223b6611adc5bd5e 
* before that commit, we get finite coefficients (intercept=6.916020 and slope=2.4876223 in this case), even when convergence was not reached.
* after that commit, we get NA coefficients when convergence is not reached.
* this makes sense -- the change fixes a typo that was preventing NA from over-writing coefficients, when convergence was not reached.
I guess this is a "feature" not a "bug" ? I was expecting the old behavior (return whatever coefficients were found, even if not converged).

**Comment by tdhock** [comment]
Now in light of https://github.com/therneau/survival/commit/ede711c5fa4ce819801d856582369ee5eea94fd6#diff-4f0d94965fe3e1440e71f9cb6d8e2bd412df4871c08f7a5f223b6611adc5bd5e which seems to imply that coefficients are set to NA when convergence does not happen, I find it surprising that for extra.id=120 data, I get the warning about not converged, but I still get finite coefficients, why?

**Comment by tdhock** [comment]
in all of these cases the data look reasonable, so it would be great if survreg would converge.

**Comment by tdhock** [comment]
A work-around is to manually specify a scale parameter, `survreg(scale=1)` instead of the default 0 which attempts to optimize the scale, and reaches a singularity because the data are separable (decreasing the scale will always increase the likelihood).
Here is a visualization,
![image](https://github.com/user-attachments/assets/07708d0d-40d4-4ee0-9d8a-0690f9b5145e)
Above the top two rows are the same as the previous figure (penaltyLearning default scale 1, survreg default scale 0).
The bottom row is survreg with scale=1, for which we get convergence in all 3 data sets.

code:
```r
library(survival)
full.df <- structure(list(id = c(1L, 1L, 1L, 1L, 1L, 1L, 4L, 4L, 4L, 4L, 
4L, 4L, 6L, 6L, 6L, 6L, 6L, 6L, 8L, 8L, 8L, 8L, 8L, 8L, 10L, 
10L, 10L, 10L, 10L, 10L, 11L, 11L, 11L, 11L, 11L, 11L, 13L, 13L, 
13L, 13L, 13L, 13L, 120L, 120L, 120L, 120L, 120L, 120L), lo = c(0.195727051766757, 
-1.1087553605429, -1.00065642410924, -0.995123241844028, -Inf, 
-1.81065319423307, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -0.694428755856871, 
-2.4887060208859, -3.44756655828744, -3.03711252743929, -3.14523459850271, 
-0.892319064459033, -0.552651313503626, -Inf, -2.43732789951484, 
-1.24650632092422, -Inf, -Inf, -1.50791410241527, -2.24743277679978, 
-2.37206425088304, -3.83417364430955, -2.60448041546997, -1.44599430482559, 
-Inf, -0.456570392651195, -0.249593970642512, -Inf, 0.552800358347374, 
1.03693235764513, 0.366866754402124, -2.52677122267308, -2.48507949525124, 
-1.54283966348088, -1.59313273785538, -2.44940446306835, -0.513882229855861, 
-3.450873922835, -3.02209394810166, -3.97458092881313, -3.57901135468839, 
-2.1845818324618), hi = c(Inf, Inf, Inf, Inf, 2.06739808397873, 
Inf, 3.26518538624204, 1.13643272732406, 2.27284346410842, 1.38565083489553, 
0.492585941448176, 2.13713710441581, Inf, Inf, Inf, Inf, Inf, 
Inf, Inf, 0.937658965079102, Inf, Inf, 3.17164978103177, 3.0679625505633, 
Inf, Inf, Inf, Inf, Inf, Inf, 2.39473287695651, Inf, Inf, 0.730793396188341, 
Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, 
Inf), feature = c(-2.65456939094638, -2.42126427679538, -2.0705540906376, 
-2.41236133374335, -2.38707136376868, -2.50995205248869, -2.36922164775071, 
-2.39136308372706, -2.35954108440544, -2.52855213967643, -2.61717785427761, 
-2.32148054113571, -2.90042209374967, -2.81341071676004, -2.90042209374967, 
-2.7646205525906, -2.97592964625781, -2.3434070875143, -2.87790396885268, 
-2.92818004477678, -2.91781583734955, -3.04532040079498, -2.44619735876083, 
-2.36685302923454, -3.17008566069877, -2.7646205525906, -2.54465665419377, 
-3.12356564506388, -3.20645330486964, -2.39689577246529, -2.43836426623075, 
-2.17187107950722, -2.52267471748792, -2.59336839058434, -1.84434871178509, 
-1.9783687469636, -3.01613697015902, -3.0756635490299, -2.93034936935621, 
-2.94970009845407, -2.89011456307748, -2.87110297166178, -3.01593498087151, 
-3.01593498087151, -2.94694210938456, -2.71055333132033, -3.11226608980994, 
-2.68824757380603)), class = "data.frame", row.names = c(NA, 
-48L))
write.csv(full.df, "~/R/survreg-data.csv", row.names=FALSE)
model.fun.list <- list(
  survreg=function(train.df, sc){
    fit <- with(train.df, survreg(
      Surv(lo, hi, type="interval2") ~ feature,
      scale=sc,
      dist="gaussian"))
    coef(fit)
  },
  penaltyLearning=function(train.df, sc){
    fit <- with(train.df, penaltyLearning::IntervalRegressionUnregularized(
      cbind(feature), cbind(lo,hi), margin=sc))
    coef(fit)[,"0"]
  })
model.df <- rbind(
  data.frame(pkg="penaltyLearning", scale=1),
  data.frame(pkg="survreg", scale=0),
  data.frame(pkg="survreg", scale=1))
dot.df.list <- list()
coef.df.list <- list()
for(extra.id in c(0,13,120)){
  sub.df <- subset(full.df, id %in% c(1, 4, 6, 8, 10, 11, extra.id))
  for(model.i in 1:nrow(model.df)){
    model.row <- model.df[model.i,]
    model.fun <- model.fun.list[[model.row$pkg]]
    sub.df <- subset(full.df, id %in% c(1, 4, 6, 8, 10, 11, extra.id))
    this.df <- data.frame(extra.id, model.row, warn.text="")
    set.warn <- function(w)this.df$warn.text <<- w$message
    set.coefs <- function(){
      weight.vec <- model.fun(sub.df, model.row$scale)
      this.df$intercept <<- weight.vec[["(Intercept)"]]
      this.df$slope <<- weight.vec[["feature"]]
    }
    withCallingHandlers(set.coefs(), warning=set.warn)
    coef.df.list[[paste(extra.id, model.i)]] <- this.df
    dot.df.list[[paste(extra.id, model.i)]] <- with(sub.df, data.frame(
      extra.id, model.row,
      rbind(
        data.frame(limit="lo", output=lo, feature),
        data.frame(limit="hi", output=hi, feature))))
  }
}
dot.df <- subset(do.call(rbind, dot.df.list), is.finite(output))
coef.df <- do.call(rbind, coef.df.list)
library(ggplot2)
ggplot()+
  theme_bw()+
  geom_abline(aes(
    slope=slope, intercept=intercept),
    data=coef.df)+
  facet_grid(pkg + scale ~ extra.id, labeller=label_both)+
  geom_point(aes(
    feature, output, fill=limit),
    shape=21,
    data=dot.df)+
  geom_text(aes(
    -3.2, 3, label=sprintf(
      "slope=%.2f\nintercept=%.2f\n%s", slope, intercept, warn.text)),
    vjust=1,
    hjust=0,
    data=coef.df)
```

**Comment by tdhock** [comment]
Also can you clarify what "singular" means in this context? The only mention I see in the docs is on ?survreg.control "toler.chol: Tolerance to declare Cholesky decomposition singular" 
On what matrix are you computing Cholesky decomposition?

**Comment by therneau** [comment]
I have been out of the office for the last 10 days, so just now looking at this.  (I was getting to know a 1 year old granddaughter, who unfortunately lives far away, and paid absolutely no attention to anything else.)

I consider "give the wrong answer" to be much worse than "fail with a message"; the prior update tried to move in that direction.  But you are correct that not failing is better.    I will look into  this, but it will be at least a week due to other commitments.

**Comment by tdhock** [comment]
The reason why penaltyLearning works in this case, is that its scale is fixed to 1 by default (not optimized).
An error message that tells the user to try specifying scale>0 would be appreciated.

**Comment by therneau** [comment]
There was an error in the code, if an infinite loglik occured step halving did not get proper invoked.  Both your data and issue 263 manage a Newton-Raphson step that gives an NA loglik.   Surprising that the two issues arose so close in time.   In any case, to my extreme surprise, proper step halving is able to give a solution for all 3 of your data sets.   Because of the flat regions of the likelhood surface the estimated variance of the estimates is huge (and worthless) however.

**Comment by tdhock** [comment]
this is great, thanks for your diligent work Terry

**Comment by tdhock** [comment]
i confirm the new code on github, https://github.com/therneau/survival/commit/bfa1b8b584e9100c2e5eaa4829638b571f639b0c works on my computer,
![image](https://github.com/user-attachments/assets/2495317b-c24c-48e1-b542-7212f0a0d940)
we see in the figure above that for the middle row of plots (scale: 0 meaning scaled optimized), we no longer get NA coefs, nor convergence warnings.
code for figure: https://tdhock.github.io/blog/2024/bisect-survival/
