### ISSUE TITLE
`survdiff()` and counting process form data

### ISSUE THREAD

**Issue by ThomasSoeiro** [therneau/survival#272]
I was trying to perform a log-rank test on counting process form data.

E.g. with the following example from `?tmerge()`:

```r
temp <- subset(pbc, id <= 312, select=c(id:sex, stage)) # baseline data
pbc2 <- tmerge(temp, temp, id=id, endpt = event(time, status))
pbc2 <- tmerge(pbc2, pbcseq, id=id, ascites = tdc(day, ascites),
               bili = tdc(day, bili), albumin = tdc(day, albumin),
               protime = tdc(day, protime), alk.phos = tdc(day, alk.phos))
```

I get the following error with `survdiff()`:

```r
survdiff(Surv(tstart, tstop, endpt==2) ~ protime, data=pbc2)
# Erreur dans survdiff(Surv(tstart, tstop, endpt == 2) ~ protime, data = pbc2) : 
#   Right censored data only
```

I first found the error message quite misleading and I finally understood that it is not supported. According to `?survdiff`:

> a formula expression as for other survival models, of the form `Surv(time, status) ~ predictors`.

Could you please confirm that `survdiff()` does not support counting process form data? If so, maybe the error message and the documentation could state more clearly that the form `Surv(tstart, tstop, status)` is not supported?

Thanks a lot for your work on `{survival}`!

PS: I have no formal training in statistics, so it may be total non-sense to try that in the first place. However, [I am not the first](https://stackoverflow.com/q/55460095).

**Comment by therneau** [comment]
For me, right censored, left censored, interval censored and counting process are 4 distinct types.   So the error message is perfectly clear.    But per your note, obviously not perfectly clear to the rest of the world.   I'll try to improve the message.

The log-rank test is equivalent to the score test from a Cox model, e.g., 
    fit <- coxph(Surv(tstart, tstop, endpt==2) ~ protime, data=pbc2)
    summary(fit)$sctest
 But--  the original log-rank was never defined for time-dependent covariates, nor for continuous ones.

**Comment by ThomasSoeiro** [comment]
Thank you very much for the explanations!

**Comment by ThomasSoeiro** [comment]
I have just tested the development version. I confirm that the message now seems perfectly clear to me. Thanks!
