### ISSUE TITLE
df in logLik.coxph

### ISSUE THREAD

**Issue by VMTdeJong** [therneau/survival#28]
It seems that logLik.coxph selects only the df of the second coefficient, when the model includes a frailty, as this example shows:

`
library(survival)
set.seed(11092017)
n <- 100
testdata <- data.frame(time = rweibull(n, shape = 1), 
                       cens = rbinom(n, 1, 0.5), 
                       x = rnorm(n), 
                       cluster = sample(1:10, size = n, replace = T))

###### # These models are the same, except for the ordering of the formula:
m1 <- coxph(Surv(time, cens) ~ frailty(cluster) + x, data = testdata)
m2 <- coxph(Surv(time, cens) ~ x + frailty(cluster), data = testdata)

###### # The likelihoods are therefore the same
all.equal(m1$loglik, m2$loglik)

###### # Yet logLik returns different df
all.equal(logLik(m2), logLik(m1))
logLik(m1)
logLik(m2)

###### # And therefore the AIC is different
AIC(m1)
AIC(m2)
###### # This is because logLik.coxph selects the second df from the model fit object, with: object$df[2]
survival:::logLik.coxph

###### # That element is different in these two objects
m1$df
m2$df

###### # I think this should be sum(object$df), just like in 
survival:::logLik.survreg

###### # Which gives the same df and likelihood for these two models:
all.equal(sum(m1$df), sum(m2$df))
all.equal(survival:::logLik.survreg(m1), survival:::logLik.survreg(m2))
survival:::logLik.survreg(m1)
survival:::logLik.survreg(m2)
`

Valentijn de Jong

**Comment by therneau** [comment]
This is a bug, fixed in my local copy.  I'll update github soon (another issues is being worked on).
