### ISSUE TITLE
Double frailty hard crashes R

### ISSUE THREAD

**Issue by FBartos** [therneau/survival#283]
Hi,

adding two fraily terms hard crashes R (tested on Windows 11 and Linux)

```
library(survival)
lungA <- lung
lungA$xxx <- sample(c("A", "B", "C"), nrow(lung), replace=TRUE)
coxph(Surv(time, status) ~ age + frailty(inst) + frailty(xxx), lungA)
```

Cheers,
Frantisek

**Comment by therneau** [comment]
The code was never designed nor intended for multiple frailty terms.   I will add a check and error message.
