### ISSUE TITLE
correct survival curve for bias - Possible?

### ISSUE THREAD

**Issue by Schmeling-M** [therneau/survival#286]
I have the following survival model:

`km.model <- survfit(Surv(AllData2020$Survivaltime, AllData2020$Is_Dead) ~ AllData2020$Status, type="kaplan-meier")`

After running the model I export it to excel like this:

`res2 <- broom::tidy(km.model)
write_xlsx(res2, paste("C:/Surv_data_","main",".xlsx"))`

After doing some correction calculations in Excel, I would like to be able to:

1. import the corrections in R, which should be trivial and 
2. loop through the surv vector in the km. model and apply the corrections

I cant figure out how to do nr. 2 point though. Is it possible to loop through the vector for a survival curve, and apply corrections? 

I think my main challenge is how to address (read and write) a single point in the vector holding the survival probabilities. 

Any suggestions?

**Comment by therneau** [comment]
survfit does not have a "type" argument.  I don't use tidyverse.    I don't use Excel.   I don't know what you mean by a "corrected survival curve".      All of which means that your question is hard to answer.

fit <-- survfit( Surv(Survivaltime, Is_Dead) ~ Status, data=AllData), is I think the proper call.

1. If your question is "how do I replace values within a survfiit object" the answer is that it is not straightforward.   It would help to know what your final goal is.
2.

**Comment by therneau** [comment]
I have found through long experience that if I don't understand the science behind a question I often give lousy advice.    I don't know the context of your question.   (Your first set of curves look a lot like a classic immortal time bias, by the way, i.e., classifying subjects by the number of treatments they eventually got, a variable not known on day 0. )   How do justify the astonishing conclusion that all the curves will be different in year 2 given that one of them is?

**Comment by Schmeling-M** [comment]
You are correct. There is actually some immortal time bias in both plots. I'm working on eliminating that, but for now, it does not seem like the correction for ITB changes much. 

I've used this definition for ITB: https://catalogofbias.org/biases/immortal-time-bias/ figure 2B, the curves you see for the treated groups (exposed) should be correct as I count time from treatment to censoring time or time of death, but the first time period for the exposed from start of experiment (discharged) to time of treatment is not yet included in the untreated group, so the untreated are influenced indirectly by ITB, but as I wrote, even when including this (plot below), the untreated group does not change much as you can see. (blue is treated and red is untreated). We have not yet made curves for treatment 1,2,3, etc. since we are a bit in doubt as to how we handle ITB when we have several treatments. If you know how this should be done, I'd be very thankful if you would share.
![ITB](https://github.com/user-attachments/assets/908569c2-7ba0-45d5-8e6c-b7a830151680)

I do not assume, that all curves will be different in year 2, only the untreated group is the one, that I assume is influenced by Healthy User bias. This would necessarily mean, that the treated groups would be influenced symmetrically in the other direction, but I can see no way, to measure or even correct for that. On this point, I think that I'm basically interested in correcting for the Healthy User bias, but I'm unsure as to how. The above is how I thought I'd attempt to do it. Is there a better way to correct for HUB?

**Comment by therneau** [comment]
This has turned into a clinical research consultation, and has little to do with the survival package.  If you want to email me offline I can perhaps comment, but you you need spend the space to more fully explain the research question.   (What is this a study of, what is the data, what is the research question, etc.)
