### ISSUE TITLE
survfit() calculates median survival in group where greater than 50% still living

### ISSUE THREAD

**Issue by kevin198930** [therneau/survival#290]
Hello,

I have a question about the survfit() function and why it is calculating a median survival value when greater than 50% of the patients in the group are still alive. I am using the survival package v3.5-0 and in my clinical column 'Deceased', Death is denoted by 1, and Alive is denoted by 0. I am using the following formula within the survfit() function:

fit_1 <- survfit(Surv(Months_elapsed, Deceased) ~ Treatment_group, data = clinical)

I have two groups, group A with 21 of the 25 patients deceased and group B with 9 of the 30 patients deceased. Group B should not have median survival calculated, since 21 of the 30 patients are still living. However, it is calculating a median survival of 16.4 months. This causes issues when I try to generate the KM-plot using 'survminer', with the survival line falling below 50% survival on the y-axis. I've included the output of survfit() below:

> fit_1
Call: survfit(formula = Surv(Months_elapsed, Deceased) ~ Treatment_group, 
    data = clinical)

                                                 
                                                 n events median 0.95LCL 0.95UCL
>Treatment_group=group_A     25     21   12.9    10.6    20.3
>Treatment_group=group_B     30      9    16.4    10.5      NA

Any help would be greatly appreciated! Thanks

**Comment by therneau** [comment]
Yes, this is quite possible if many of the 30 are censored  before 15 months.   Your question is a statsitical one, not code.
