### ISSUE TITLE
Survdiff() error

### ISSUE THREAD

**Issue by ranrutenberg** [therneau/survival#31]
Hello,

As reported in [https://github.com/kassambara/survminer/issues/203](https://github.com/kassambara/survminer/issues/203)
the survdiff() function returns the following error 
Error in survdiff.fit(y, groups, strata.keep, rho) : 
  object 'Csurvdiff2' not found

R version 3.4.2 (2017-09-28)
Survival version 3.41-3

Sincerely,
Ran

**Comment by ranrutenberg** [comment]
I uninstalled R and deleted all packages. After reinstalling the problem was gone.

**Comment by fvermeij** [comment]
In case anyone else runs into this issue, what worked for me was reinstalling the survival package, simply running `install.packages('survival')`. That may be a good step to try first instead of completely reinstalling R and all other packages, for anyone else running into this issue.
