### ISSUE TITLE
plot.survfit: tick mark missing if coincident with dead time

### ISSUE THREAD

**Issue by ownhardy** [therneau/survival#34]
When I plot a Kaplan-Maier survival plot with data where one dead time coincides with a drop out time, then the tick mark for this drop out is NOT plotted.

I have read the doc string of plot.surv, and it says this is intentional:
mark.time	: .. If TRUE, then curves are marked at each censoring time which is not also a death time...

I find this missing tick mark very disturbing. A dop out time at a slightly different point time would have still generated the tick mark. And it is unclear (for me as user) that this unlucky event (the coincidence of a "death" and a drop out) has happened at all. No warning, nothing.

Is there a good reason to do the plot this way? Or could this be changed to a more "expected behavior"?

**Comment by therneau** [comment]
99% or more of the time those tick marks are a visual nuisance, and most of us leave them off entirely on all of our KM plots.   The plot is designed to be useful in practice, it is not a substiute for the data itself, and reflects many design choices that arose of several decades in our department.   Some are very good, some of the design choices are proably just tradition.  Tick marks at the exact corners of the step function tend to introduce visual noise, or at least that is the local opinion.  It is obviously not your opinion, which is okay.  The definition of "visually pleasing" is a subjective one.

You are not the first to want something different in the plots.  You might take a look at the survminer package, which has many fans.  There is survplot in the rms package, the autoplot function in ggfortify,  ggsurv in the ggally package, the Kmsuv package, and  I expect there are many others that I have missed.

I focus most of my energy in the survival package on accuracy.  The code is extensively tested to ensure that it gives the right answer.  I then provide simple print, plot and summary functions (good enough for me), but also carefully document exactly what is contained in each output object so other users can write their own extensions.   One only has so much time.

  On a practical note, exactly where should that mark be placed on the vertical rise?  Top, bottom, midpoint, elsewhere?

Terry T.

**Comment by ownhardy** [comment]
Thank you for pointing me to other packages that can create Kaplan-Meier plots. Currently, I will still stick to your package, and work around this behavior by manually changeing my data slightly.

In general, I can see that the tick marks get distracting, when there are many. But in my case there aren't many data points at all, so the tick marks look fine, actually. Also in my case people can check by eye that something is missing if I omit one of the tick marks, since there aren't so many data points at all. But for this case, your function leaves me (and other user) the choice to either turn those check marks on or off, fine.

I would like to argue, that once those check marks are turned on, I'd rather see all of them and not just most of them. (My personal perception is even that unexpectedly skipping one of the tick marks, is an "inaccuracy" in the plot.)  For my expectations it would be good to put the check marks that coincide with "death" steps at the lower right end of the step. (Because the drop outs actually still turned up at this point of time, they really dropped out of my observation at a later but unknown point of time.)

Please take my message only as a feedback from a user of your package. I don't want to stress that your code is doing anything "wrong". I would just like to let you know why my expectations weren't met in my special case. I can fully understand if your emphasis is at a different area (exactness in your case) and not in "beautiful" plots.

Thanks for generating this R package at all!

**Comment by therneau** [comment]
Some other comments arrived with the same complaint.  So I have relented and changed it.  (See Luke 18:1-8, the parable of the unjust judge.)
