### ISSUE TITLE
Citations missing in "Validation" vignette

### ISSUE THREAD

**Issue by mkoohafkan** [therneau/survival#36]
The bibliography is missing from the vignette.

**Comment by therneau** [comment]
There are no citations in that vignette, so there is nothing to put into a bibliography.  Are you arguing that I should refer so other papers?  If so which?

**Comment by mkoohafkan** [comment]
The validation vignette does indeed include references, e.g. the reference to  Therneau and Grambsch in the last paragraph of the introduction. However, the actual citation is missing, which is why `[?]` appears after the reference.

**Comment by therneau** [comment]
You are right.  I had searched for "cite" using my text editor and came up empty -- I must have mistyped my search.  Thanks for the persistence.

**Comment by therneau** [comment]
This is now repaired.
