### ISSUE TITLE
Coxph error: Error in fitter(X, Y, strats, offset, init, control, weights = weights,: routine failed due to numeric overflow.

### ISSUE THREAD

**Issue by DanaiChas** [therneau/survival#37]
I'm using the risksetROC() function for some coxph predictions. I Got the error message:
_Error in fitter(X, Y, strats, offset, init, control, weights = weights,  : 
routine failed due to numeric overflow.This should never happen.  Please contact the author._

Going through the source code of risksetROC, I realized that, the error comes from the coxph() function. Specifically: coxph(Surv(time, time2, status)~eta)

Could you please help me understand why my data gives this error?
If needed I can provide he data that I give as an input.

**Comment by therneau** [comment]
Try the version I just posted.   Some functions that create a lot of (start,stop) intervals will create multiple unnecessary ones, and there was a hard to create bug in that case.

**Comment by sdaza** [comment]
Was this issue solved? I have the same problem.

**Comment by therneau** [comment]
Try following the suggestion of "please contact the author".  Github comments don't count.

**Comment by rcragun** [comment]
If Github bug reports do not count, then what does?

**Comment by therneau** [comment]
It said "please contact the author", by which I mean email.  There isn't one 'solution' to the issue.  Data sets that produce numeric overflow/underflow are all special edge cases, and  require a data set that demonstrates the issue.  That is simply easier to deal with using email.
There is a whole directory "fail" containing data sets that push the numeric envelope.  Each of them allowed me to harden the code a bit more.
