### ISSUE TITLE
Catching id NA error in tmerge

### ISSUE THREAD

**Issue by maratotm** [therneau/survival#39]
Just a simple addition that might be useful is to catch the error when there are null id's in the input for tmerge function. A more useful error message will save a bit of time. Hope this helps.

Example:
```library(survival)
temp <- subset(pbc, id <= 312, select=c(id:sex, stage)) # baseline data

# Including the source of error
temp[temp$id==1, "id"] = NA 

pbc2 <- tmerge(temp, temp, id=id, endpt = event(time, status))
```
Current error message:
```
Error in if (length(baseid) == length(id) && all(baseid == id)) newdata <- data1 else { : 
missing value where TRUE/FALSE needed
```

**Comment by therneau** [comment]
Updated the message to be "id variable cannot have missing values".
Thanks for the input.
