### ISSUE TITLE
Error from survfit and survdiff when strata column name has space

### ISSUE THREAD

**Issue by hideaki** [therneau/survival#41]
Hi,
I'm getting error when strata column has space in its name.
It reproduces with the following script.

```
library(survival)
library(dplyr)

lung2 <- lung %>% mutate(`se x`=sex) # insert space in column name

survfit(Surv(time,status)~`se x`,data=lung2)
# Error in `[.data.frame`(m, ll) : undefined columns selected

survdiff(Surv(time,status)~`se x`,data=lung2)
# Error in `[.data.frame`(m, ll) : undefined columns selected
```

**Comment by therneau** [comment]
This generated a long discussion on r-devel, a summary of which is that this is really hard to fix, since it has to do with how R creates the model.frame and terms objects.  The short answer then is -- don't use spaces in your variable names!

**Comment by ViniciusBRodrigues** [comment]
> This generated a long discussion on r-devel, a summary of which is that this is really hard to fix, since it has to do with how R creates the model.frame and terms objects. The short answer then is -- don't use spaces in your variable names!

I'm not using space in my variables names and getting the same error.

**Comment by therneau** [comment]
Without a concrete example, it is impossible to respond in any meaningful way.

**Comment by dBenedek** [comment]
Hi, for me when I renamed my variable to not include spaces the error disappeared.

**Comment by joshkell** [comment]
I had the same issue. Once I renamed the variable not to include a space the error also disappeared.
