### ISSUE TITLE
Confidence intervals for random intercept 

### ISSUE THREAD

**Issue by TiagoVentura** [therneau/survival#42]
Dear Prof. Therneau,

I am using the coxme packages to estimate frailty models. However, I am struggling with something that might be stupid, but I decided to ask here anyway. How can I build confidence intervals for the variance of the random effects? The output of the models gives me only the variance and the std deviation for the random effects(intercept), but I was planning to plot the coefficients with confidence intervals. 

thank you!

**Comment by therneau** [comment]
This is a statistical issue, whose primary answer is "I don't know any theory that allows me to give an answer".  
I would prefer stat queries to the author, rather than in the code repository.  (I don't log into github very often).
