### ISSUE TITLE
survfit errors with `DataFrame`

### ISSUE THREAD

**Issue by LiNk-NY** [therneau/survival#46]
Hi Terry,

Thank you for working on this package. 
I have an issue when running `survfit` on an `S4Vectors::DataFrame`.
It has something to do with the way you're accessing symbols in the `data` argument. 
It could be that this method is too specific for `data.frame`s and not broad enough to
support other classes by default. 

Example with `data.frame` works fine
```
library(survival)
data(lung)
lung$surv1 <- with(lung, Surv(time, status))
head(lung)
survfit(surv1 ~ age, data = lung)
```
but with `S4Vectors`: 

```
## Install Bioconductor first
## install.packages("BiocManager")
## BiocManager::install("S4Vectors", version = "3.8")
library(S4Vectors)
ll <- as(lung, "DataFrame")
ll$surv1 <- with(ll, Surv(time, status))
head(ll)
survfit(surv1 ~ age, data = ll)
```
**Error**:

```
> survfit(surv1 ~ age, data = ll)
Error in eval(predvars, data, env) : object 'surv1' not found
```
The code should be looking for 'surv1' in `ll`. 

Thank you for your attention. 
Best regards,
Marcel

**Comment by therneau** [comment]
This is not a problem with survival, but a problem with the pseudo data frames created by "DataFrame".  They do not store complex objects in the way that the model.frame function in R expects; and model.frame() is underneath the formulas in nearly every modeling function.   You should direct this to a bioconductor list or to the author of the DataFrame method. 
An example that doesn't use survival:
library(splines)
library(S4Vectors)
test <- longley
test$year2 <- ns(test$Year, 3)
lm(GNP ~ Unemployed + year2, test)   # error  "year2 not found"
