### ISSUE TITLE
head and tail method for Surv objects

### ISSUE THREAD

**Issue by LiNk-NY** [therneau/survival#48]
Hi Terry, @therneau 

I've recently tried to use a `DataFrame` with embedded `Surv` objects. 
It seems like `Surv` objects are not behaving as expected when using `head` and `tail`.
Would you be willing to these methods to `Surv` class objects?

See more here: Bioconductor/S4Vectors#17

Regards,
Marcel

**Comment by therneau** [comment]
Multiple methods have now been added for Surv objects, including head and tail.
