### ISSUE TITLE
Handling of factors with anova.coxph 

### ISSUE THREAD

**Issue by bprehn219** [therneau/survival#49]
Line 109 of survival/R/anova.coxph.R returns this error:
`Error in ``row.names<-.data.frame``(``*tmp*``, value = c("NULL", "twi:seasonperiod",  : 
  invalid 'row.names' length`

My model included a factor as an interaction term for all independent variables like so:

` clogit(response ~ (continuous1 + continuous2 + ....):factor + strata..... )  `

Changing the model form to the following fixes the issue:
` clogit(response ~ continuous1 + continuous2 + (continuous1 + continuous2 + ....):factor + strata..... )  `

My understanding is that those are the same model when a factor is the interaction term.

Brandon

**Comment by therneau** [comment]
Note that the two models are not the same, and you can easily see by creating a simple data frame and fitting an lm model.
Still, the error message should not occur.

**Comment by therneau** [comment]
This error no longer occurs in the current version (at least for my test case).   Let me know if you have an example data set that does.
