### ISSUE TITLE
tmerge and characters

### ISSUE THREAD

**Issue by CMcCort** [therneau/survival#52]
Thank you for the survival package.

I think I have found a bug in `tmerge ()` with `tdc()` and character covariates.

```R
library(survival)
d1 <- data.frame(id = 1:2, time = 100, 
                 status = 0:1, 
                 char = letters[1:2], 
                 stringsAsFactors = FALSE) # works fine with factors

test <- tmerge(d1[,1,drop = FALSE], d1, id = id, 
               outcome = event(time,status), 
               cov = tdc(c(0,0),char))

# Warning message:
# NAs introduced by coercion 
```
I think line 539 of tmerge.Rnw should have `y2[keep]` instead of `yinc[keep]`.

**Comment by therneau** [comment]
I will look at this.  I was out of town (out of the country) for 3 weeks and am still catching up.  This isn't in my test suite because I never thought of a tdc character; but it is a perfectly rational request.

**Comment by therneau** [comment]
You are correct.  Now fixed.
