### ISSUE TITLE
pval.txt is "0.05" for surv_pvalue()

### ISSUE THREAD

**Issue by victorn1** [therneau/survival#56]
When p-value is, say, 0.0504 or 0.0499 the `surv_pvalue()` returns "0.05" as `pval.txt`. The reported information is usually insufficient, so one has to insert the p-value manually into the plots. I suggest that there be an argument `alpha` with default value 0.05 such that `surv_pvalue()$pval.txt` will display all the necessary digits around `alpha`, so that one can read whether the p-value is greater or lesser than `alpha`.

**Comment by therneau** [comment]
There is no surv_pvalue function in the survival package.   I think you have this mixed up with something else.
