### ISSUE TITLE
model.frame.coxph strips attributes for factor variables

### ISSUE THREAD

**Issue by ddsjoberg** [therneau/survival#60]
First, thank you for the great package!  

The `model.frame.coxph()` (and also `model.frame.survreg()`) strip attributes for factor variables, but not other types of variables.  In the example below, the covariates (where age is numeric, and sex is a factor) have attributes in the data frame that is provided to `coxph()`.  If I run `model.frame()` on the coxph object, the attributes are stripped for sex, but are remain for age.  Would it be possible to have the attributes for factor variables returned as well?

Thank you!

``` r
library(survival)
# saving copy of lung and making sex a factor
lung2 <- lung[c("time", "status", "sex", "age")]
# making sex a factor
lung2$sex <- factor(lung2$sex)


# adding attribute labels (implemented in common packages, eg Hmisc, haven, and labelled)
attr(lung2$sex, "label") <- "Male=1 Female=2"
attr(lung2$age, "label") <- "Age in years"

# printing label attributes for model covariates
lapply(c("sex", "age"), function(x) attr(lung2[[x]], "label"))
#> [[1]]
#> [1] "Male=1 Female=2"
#> 
#> [[2]]
#> [1] "Age in years"

# building cox model
m1 = coxph(Surv(time, status) ~ sex + age,  lung2)

# saving lung data from model.frame
lung3 <- model.frame(m1)

# printing attribute labels, but factor variable sex had attribute stripped
lapply(c("sex", "age"), function(x) attr(lung3[[x]], "label"))
#> [[1]]
#> NULL
#> 
#> [[2]]
#> [1] "Age in years"

# other regression modeling functions preserve attributes with model.frame
m2 = lm(time ~ sex + age, lung2)
lung4 = model.frame(m2)
lapply(c("sex", "age"), function(x) attr(lung4[[x]], "label"))
#> [[1]]
#> [1] "Male=1 Female=2"
#> 
#> [[2]]
#> [1] "Age in years"
```

<sup>Created on 2019-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by therneau** [comment]
The default for coxph is model= FALSE, for lm it is model=TRUE.
If you call lm with model=FALSE, you will get the same behavior you describe for coxph.
If you call coxph with model=TRUE, you will have the label preserved.   

No, I don't know why the label disappears when the model frame is rebuilt.
