### ISSUE TITLE
Survreg errors when fitting a AFT model with random effects (using frailty)

### ISSUE THREAD

**Issue by ChuangshiWang** [therneau/survival#62]
Hi,

How is going?
First thank you for your contributions on survival package and I am a big fan. When I fit a AFT model with random effects (using frailty function), I came across the erros as follows:

Error in coxph.wtest(hinv.full[i, i], var[i, i]) : 
  NA/NaN/Inf in foreign function call (arg 4) 
10.
coxph.wtest(hinv.full[i, i], var[i, i]) 
9.
coxpenal.df(matrix(fit$hmat, ncol = nvar2), matrix(fit$hinv, 
    ncol = nvar2), hdiag, assign, ptype, nvar2, temp1, temp2, 
    pindex[sparse]) 
8.
survpenal.fit(X, Y, weights, offset, init = init, controlvals = control, 
    dist = dlist, scale = scale, strata = strata, nstrat = nstrata, 
    pcols, pattr, parms = parms, assign) 
7.
survreg(formula = Surv(time, status) ~ Z1 + frailty.gamma(family), 
    dist = "weibull", data = structure(list(family = c(1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  ...
...

I googled the error but did not find any valuable information. I also read the closed issues and found one similar issue (having errors when fit AFT model using data with open intervals) I guess we have similar questions: it says something about "coxph" but I am not fitting a Cox model.. I want to fit a parametric AFT model with random effects. In that thread (https://github.com/therneau/survival/issues/8) , it says this is a bug which will be fixed in the next version. I've already updated my survival package to the latest one. 
The second question is that the estimated coefficient is NA without errors like:
Call:
survreg(formula = Surv(time, status) ~ Z1 + frailty.gamma(family), 
    data = testdata, dist = "weibull")

                      coef se(coef) se2 Chisq DF p 
(Intercept)                 0        0        1    
Z1                          0        0        1    
frailty.gamma(family)                    0    0   1

Scale= NA 

Iterations: 10 outer, 134 Newton-Raphson
     Variance of random effect= 5e-15   I-likelihood = -342.5 
Degrees of freedom for terms= NaN NaN   0 NaN 
Likelihood ratio test=-191  on NaN df, p=NA  n= 200 
What could be the reason?

It's kind of urgent but not sure where is the problem ? could you help check this out? Thank you so much.

**Comment by therneau** [comment]
The survreg routine does not support random effects.
