### ISSUE TITLE
When model contains time dependent covariates, do we need to valuate proportional hazards assumption

### ISSUE THREAD

**Issue by Victorfy** [therneau/survival#63]
I have done survival analysis in R using cox model.  My datasets contains time dependent covariates(tdc), it likes `newcgd` data in [timedep.pdf](https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf), according to it,  I built the model successfully.

But when I used `cox.zph` function to valuate cox assumption, there were some items violated proportional hazards assumption. 

So Q1: Do we need to valuate assumption when contains tdc? In the cgd example, when build the model successfully, it doesn't valuate cox assumption.

Q2: If use cox.zph to valuate assumption is right, how to handle these items violated assumption, is it a problem with time dependent covariates and time dependent coefficients simultaneously? How to solve it using cox model? timedep didn't give the answer.

**Comment by therneau** [comment]
This is not an issue with the package, it is a request for a data analysis tutorial.   In short, proportional hazards can be violated with time-dependent covariates, the cox.zph test is still valid.  When violations exist, the first step is to THINK.   The best way to proceed depends on your study and the question that it is trying to answer.   These are all tools to help someone understand the data.
