### ISSUE TITLE
predict.coxph fails when newdata is given using a model estimated with offset and cluster

### ISSUE THREAD

**Issue by jvasilakes-umn** [therneau/survival#64]
predict.coxph() throws an error when passing the newdata arg and when using a model whose formula uses both offset() and cluster(). The error does not occur when using just offset(), just cluster(), or neither. A small reproducible example follows. Thanks.

```
library(survival)
attach(lung)
m <- coxph(Surv(time, status) ~ age + sex + offset(ph.karno) + cluster(inst), data=lung)
p <- predict(m)  # This works
p.newdata <- predict(m, newdata=lung)  # This fails
```

The exact error is
```
Error in model.frame.default(data = lung, formula = ~age + sex, na.action = function (object,  : 
  number of variables != number of variable names
```

Output of sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survival_2.44-1.1

loaded via a namespace (and not attached):
[1] compiler_3.5.1  Matrix_1.2-14   tools_3.5.1     splines_3.5.1   grid_3.5.1      lattice_0.20-38

**Comment by therneau** [comment]
It's a bug in my use of untangle.specials, it's been there a long time, and could harm any fit with a formula with offset() earlier than one of cluster, tt, or strtata.   It's amazing that no one ever noticed before.

Terry T.

**Comment by jvasilakes-umn** [comment]
Thanks for the prompt response. You mention that the issues occurs in formulas with offset earlier than cluster. Would there be any issue switching the order? E.g. instead of my example above
```
m <- coxph(Surv(time, status) ~ age + sex + cluster(inst) + offset(ph.karno), data=lung)
```
as I notice this does not raise the error when passing newdata.

**Comment by therneau** [comment]
The issue is actually with [.terms, part of base R.  I've filed a bugzilla report.

**Comment by therneau** [comment]
This is now repaired.
