### ISSUE TITLE
residuals.survreg issues

### ISSUE THREAD

**Issue by devoges** [therneau/survival#65]
I think I've noticed an issue in `residuals.survreg` that I'll mention here.

For the "dfbetas" type, there is a line: 

`rr <- rr %*% diag(1/sqrt(diag(vv)))`

This removes the column names. Just replacing with

`rr[] <- rr %*% diag(1/sqrt(diag(vv)))`

keeps the names.

**Comment by therneau** [comment]
Thank you for the suggestion.  Now changed in my master copy.
