### ISSUE TITLE
Confidence intervals missing

### ISSUE THREAD

**Issue by rdinter** [therneau/survival#66]
Confidence intervals are no longer calculated:

``` r

library("survival")

sr <- survreg(
  Surv(futime, fustat) ~ ecog.ps + rx,
  ovarian,
  dist = "exponential"
)

confint(sr)
#>             2.5 % 97.5 %
#> (Intercept)    NA     NA
#> ecog.ps        NA     NA
#> rx             NA     NA

confint(sr, level = .99)
#>             0.5 % 99.5 %
#> (Intercept)    NA     NA
#> ecog.ps        NA     NA
#> rx             NA     NA
```

<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by therneau** [comment]
The confint function was added to library(stats) long after survreg was written.  It assumes that the variance-covariance matrix will have the same dimnames as the coefficients vector.    I don't agree with that assumption, but will bend with the wind and update it.
