### ISSUE TITLE
clogit much slower since 2.43

### ISSUE THREAD

**Issue by izahn** [therneau/survival#67]
We noticed that `clogit` is much slower in recent `survival` package releases. The following demonstrates that `clogit` in version 2.42-6 fit a particular model in less than half a second, while the same model in version 2.44-1 took 72 seconds. 

```
library(survival)

sessionInfo()$otherPkgs$survival$Version
## [1] "2.44-1.1"

N  <- 100000
ng <- 50000

exd <-data.frame(
  g=rep(1:ng, each = N/ng),
  out=rep(0L:1L,N/2),
  x=sample(0L:1L, N/2, prob = c(.8, .2),
           replace = TRUE))

system.time({
  mod <- clogit(out ~ x + strata(g),
                method="exact",
                data = exd)
})

##   user  system elapsed 
##  71.769   0.000  71.805 

detach(package:survival)

library(devtools)

dev_mode(on = TRUE)

install_version("survival", "2.42-6")

library(survival)

sessionInfo()$otherPkgs$survival$Version
## [1] "2.42-6"

system.time({
  mod <- clogit(out ~ x + strata(g),
                method="exact",
                data = exd)
})

##   user  system elapsed 
##  0.432   0.023   0.341 
 ```

**Comment by therneau** [comment]
Thanks for the feedback.  It turns out that concordance is very slow with a large number of strata.  This wasn't part of my test cases so I hadn't noticed.  I will follow up.

**Comment by izahn** [comment]
Thanks, let me know if there is anything I can do to help!

**Comment by therneau** [comment]
This has been addressed via the keepstrata argument to conocordance.
