### ISSUE TITLE
Error in log scaled x axis

### ISSUE THREAD

**Issue by Entopic** [therneau/survival#68]
While drawing log minus log plot, there's an error accounted as follows, 

> ##### error in log x scale
> library(MASS)
> data (gehan)
> ##### error in log x scale
> library(MASS)
> data (gehan)
> gehansurv = Surv(gehan$time, gehan$cens)
> plot(survfit(gehansurv ~ gehan$treat), col=c("black", "red"), fun="cloglog")
Warning message:
In xy.coords(x, y, xlabel, ylabel, log) :
  1 x value <= 0 omitted from logarithmic plot
> myfun=function(p){return(log(-log(p)))}
> plot(survfit(gehansurv ~ gehan$treat), col=c("black", "red"), fun=myfun, log="x")
Warning message:
In xy.coords(x, y, xlabel, ylabel, log) :
  1 x value <= 0 omitted from logarithmic plot
> plot(survfit(gehansurv ~ gehan$treat), col=c("black", "red"), fun=myfun)
> 

The error continues even with time=1 removed data.

With previous version of survival package (ver 2.42-3), it works perfectly without any error.

**Comment by therneau** [comment]
Repaired in survival 3.0
