### ISSUE TITLE
Aalen additive hazard models running too slow on R 3.6.0

### ISSUE THREAD

**Issue by spenafajuri** [therneau/survival#69]
Dear all,

I'm using Aalen additive hazard models in a dataset of 55,000 participants of health examination surveys. Fitting a model with 7 variables takes 7 minutes and 35 secs. In an expanded dataset for causal mediation analysis, a similar code has been running for days in a Linux 64GB cluster machine.

Any ideas how I could run the model faster? Or perhaps consider how to optimize the code to speed up the process.

Best wishes,
Sebastián

**Comment by therneau** [comment]
I rarely if ever use the aareg function: everything it does is now done in more generality by the timereg package.  I would look there.

**Comment by spenafajuri** [comment]
Dear Prof. Therneau,

I am using aalen in timereg. The aareg function only fits a non-parametric and its only useful to check time-varying effects

Best wishes,
Sebastián

**Comment by therneau** [comment]
If you are not using this package, then why did you post it as an "issue" with this package!

**Comment by spenafajuri** [comment]
Oh, you are right. I am so sorry!

Sebastián
