### ISSUE TITLE
Undefined 'indx' in if-branch within predict.coxph.penal

### ISSUE THREAD

**Issue by camdenlo** [therneau/survival#70]
I think this is a minimal-impact issue because it occurs when fitting a model with only a ~penalty~ sparse term.

In predict.coxph.penal, there's an if-branch starting with "if (nvar==1)". Inside that branch, the variable "indx" is used to calculate "se", but "indx" is only defined if the preceding if-branch executed.

https://github.com/therneau/survival/blob/a676f5ec6959bc54e32c2dac94c9c336e1f08370/R/predict.coxph.penal.S#L47

An error ("object 'indx' not found") occurs if, for example, the newdata argument is supplied to predict.coxph.penal so that the if-branch where "indx" gets defined is skipped. To reproduce the error:

```
library(survival)
data.fit <- mgus2
# Add fake study site numbers
data.fit$site <- sample(1:100, nrow(mgus2), replace = TRUE)
# Fit with only random effect
fit <- coxph(Surv(futime, death) ~ frailty(site), data = data.fit)
# Create dataset with desired prediction time
data.pred <- data.frame(site = 1, futime = 10, death = 0)
predict(fit, type = "expected", newdata = data.pred)
```

Defining 'indx' results in no error (though there seems to be a problem with the output of predict in this case; I'm creating another issue for that):

```
indx <- data.pred$site
predict(fit, type = "expected", newdata = data.pred)
```

**Comment by therneau** [comment]
This has been fixed
