### ISSUE TITLE
survreg with Weibull distribution choice and heavy-tailed errors

### ISSUE THREAD

**Issue by rsparapa** [therneau/survival#72]
First of all, the survival package is indispensable and I could not do my job without it.  And, the survreg function is great: I use it practically every day.  However, I have an issue that I think can be easily addressed.  I have been looking at the survreg documentation and code but I just don't know how to do what I want.  Suppose that you generate data with heavy-tailed errors like so...
```
s <- function(x) (x*(x < 0)+3)
n <- 500
set.seed(34)
x <- sort(runif(n, -3, 3))
y <- rcauchy(n, x^3, s(x))
times <- exp(y) ## line 6
summary(times)
fit <- survreg(Surv(time=times, event=rep(1, n))~1, dist='weibull')
```
Notice that one of the times responses has over-flowed to infinity.  So, the last line will generate an error...
```
Error in survreg(Surv(time = times, event = rep(1, n)) ~ 1, dist = "weibull") : 
  Invalid survival times for this distribution
```
But, as I understand from reading the documentation, the Weibull fit is actually fitting y=log(times) rather than times=exp(y).  If so, then the exponentiation on line 6 of the code above is unnecessary and the overflow with corresponding error could be avoided.  So, how can I pass y=log(times) to survreg instead of times=exp(y) and avoid the overflow?  Can this be done with current survreg or does it require a new option or code change?  Thanks

**Comment by therneau** [comment]
Use dist='extreme'.
