### ISSUE TITLE
R 3.60 clogit not returning R2

### ISSUE THREAD

**Issue by KMaca** [therneau/survival#73]
Hello, 

I've been using the clogit function in R 3.5.1 for a while now. Just upgraded to 3.6.0
I'm noticing some inconsistencies in the clogit function. By switching between R packages I get different outputs in regards to concordance SE and R2. All input data remains the same, the only change is brought about by switching R packages. 

Is there a new way to call for R2 in R 3.6.0? Which concordance SE should I believe? 

**R 3.5.1** 
Using method = "efron"
returns Concordance (with a large standard error) and R2 
![image](https://user-images.githubusercontent.com/52187411/60067163-c5ef5c00-96c6-11e9-920b-00eba481a39d.png)

**R 3.6.0** 
Using any method = efron" or not
Returns only Concordance (with a small standard error) 
No R2 

![image](https://user-images.githubusercontent.com/52187411/60067232-14045f80-96c7-11e9-89fd-f29a188169f7.png)
![image](https://user-images.githubusercontent.com/52187411/60067388-8d9c4d80-96c7-11e9-84f7-976a2b79b265.png)

**Comment by therneau** [comment]
The Nagelkirke R^2 has been removed from coxph, and it is a long overdue change.  The measure looked promising when first proposed, but later work showed it is not a good measure of association.
