### ISSUE TITLE
timefix option in coxph

### ISSUE THREAD

**Issue by tobiasmuetze** [therneau/survival#76]
I am currently trying to use the `timefix` option for `coxph` in the survival package version 2.44-1.1 but I get the error that an interval has effective length 0. In my opinion, the problem is that the `docount` function which is defined in the `concordancefit` function calls `survfit` without the `timefix` statement. Adding `timefix = timefix` to line 151 in the file concordance.R fixes the problem. Below a minimal example for reproducing the error. 

```
rm(list = ls())

library(survival)
sessionInfo()$otherPkgs$survival$Version

x <- data.frame(time = c(1e-10, 1.1e-10, 0, 1), 
                time2 = c(2e-10, 2.2e-10, 2, 4), 
                event = c(1, 1, 1, 1), 
                trt = c(1, 0, 1, 1))

# The code does not run in R 3.4.3 with survival_2.44-1.1 and results in the error message
# "Error in aeqSurv(Y) : aeqSurv exception, an interval has effective length 0"
coxph(Surv(time = time, time2 = time2, event) ~ trt, data = x, control = coxph.control(timefix = FALSE))
```

**Comment by therneau** [comment]
Thank you for excellent detective work.  Now fixed in survival 3.0-6.  I'm still working out a test suite issue, but it should be pushed to github this week.
