### ISSUE TITLE
Compilation error on windows (undefined references to concordance1 and concordance2)

### ISSUE THREAD

**Issue by mnel** [therneau/survival#77]
I am attempting to build / install on Windows 10, R 3.6.1 

I have run 'make fun' within the noweb subdirectory,

Then run
R CMD build ....
R CMD INSTALL survival_3.0-8.tar.gz [results below]

* installing to library 'C:/R/R-3.6.1/library'
* installing *source* package 'survival' ...
** using staged installation
** libs

*** arch - i386
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agexact.c -o agexact.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agfit4.c -o agfit4.o
agfit4.c: In function 'agfit4':
agfit4.c:575:24: warning: 'dtime' may be used uninitialized in this function [-Wmaybe-uninitiali
zed]
                     if (tstop[p] < dtime) break; /* no more to add */
                        ^
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agfit5.c -o agfit5.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agmart.c -o agmart.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agmart2.c -o agmart2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agmart3.c -o agmart3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agscore.c -o agscore.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agsurv3.c -o agsurv3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agsurv4.c -o agsurv4.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c agsurv5.c -o agsurv5.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c chinv2.c -o chinv2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c chinv3.c -o chinv3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c cholesky2.c -o cholesky2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c cholesky3.c -o cholesky3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c cholesky5.c -o cholesky5.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c chsolve2.c -o chsolve2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c chsolve3.c -o chsolve3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c chsolve5.c -o chsolve5.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c concordance3.c -o concordance3.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c cox_Rcallback.c -o cox_Rcallback.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxcount1.c -o coxcount1.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxdetail.c -o coxdetail.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxexact.c -o coxexact.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxfit5.c -o coxfit5.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxfit6.c -o coxfit6.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxmart.c -o coxmart.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxmart2.c -o coxmart2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxph_wtest.c -o coxph_wtest.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxsafe.c -o coxsafe.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxscho.c -o coxscho.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxscore.c -o coxscore.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxsurv1.c -o coxsurv1.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c coxsurv2.c -o coxsurv2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c dmatrix.c -o dmatrix.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c doloop.c -o doloop.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c finegray.c -o finegray.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c gchol.c -o gchol.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c multicheck.c -o multicheck.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c norisk.c -o norisk.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c pyears1.c -o pyears1.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c pyears2.c -o pyears2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c pyears3b.c -o pyears3b.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c pystep.c -o pystep.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survConcordance.c -o survConcordance.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survdiff2.c -o survdiff2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survfit4.c -o survfit4.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survfitci.c -o survfitci.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survfitkm.c -o survfitkm.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survpenal.c -o survpenal.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survreg6.c -o survreg6.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survreg7.c -o survreg7.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survregc1.c -o survregc1.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survregc2.c -o survregc2.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c survsplit.c -o survsplit.o
c:/Rtools/Rtools35/mingw_32/bin/gcc  -I"C:/R/R-3.6.1/include" -DNDEBUG          -O3 -Wall  -std=
gnu99 -mtune=generic -c tmerge.c -o tmerge.o
c:/Rtools/Rtools35/mingw_32/bin/gcc -shared -s -static-libgcc -o survival.dll tmp.def agexact.o
agfit4.o agfit5.o agmart.o agmart2.o agmart3.o agscore.o agsurv3.o agsurv4.o agsurv5.o chinv2.o
chinv3.o cholesky2.o cholesky3.o cholesky5.o chsolve2.o chsolve3.o chsolve5.o concordance3.o cox
_Rcallback.o coxcount1.o coxdetail.o coxexact.o coxfit5.o coxfit6.o coxmart.o coxmart2.o coxph_w
test.o coxsafe.o coxscho.o coxscore.o coxsurv1.o coxsurv2.o dmatrix.o doloop.o finegray.o gchol.
o init.o multicheck.o norisk.o pyears1.o pyears2.o pyears3b.o pystep.o survConcordance.o survdif
f2.o survfit4.o survfitci.o survfitkm.o survpenal.o survreg6.o survreg7.o survregc1.o survregc2.
o survsplit.o tmerge.o -LC:/R/R-3.6.1/bin/i386 -lR
init.o:init.c:(.rdata+0x15c): undefined reference to `concordance1'
init.o:init.c:(.rdata+0x168): undefined reference to `concordance2'
collect2.exe: error: ld returned 1 exit status
no DLL was created

I can see that the Makefile was edited [with respected to concordance1,c in https://github.com/therneau/survival/commit/17858cb49da311a82c226d652fd898c6177b288f#diff-060b9d5a502c6278145d1156fd4291c7 

The readme document references a 'configure' script [but unless this means  the makefile within noweb, I can't see it within the github repository...]

Is there a step after 'make fun' than updated init.c appropriately?

**Comment by mnel** [comment]
Editing the makefile [to include concordance2.Rnw and concordance1.c
fixing  couple of syntax issues in the generated concordance.r 
then editing namespace to not export survConcordance allowed it to compile without error

**Comment by therneau** [comment]
Thanks for the report.  These are all components of survConcordance, which will one day be depricated.  (It has been replaced by the more general concordance function. )  But that hasn't happened yet, and I got ahead of myself in removing it from the Makefile.   I've now addressed the issue.
