### ISSUE TITLE
Help with aeqSurv(Y) error

### ISSUE THREAD

**Issue by geraldinekoh** [therneau/survival#78]
Would require help in debugging the error: Error in aeqSurv(Y) : 
  aeqSurv exception, an interval has effective length 0

I read some post saying that we can set timefix = FALSE to resolve the issue. However, I still get this error even after including it. Below is my code:

# create survival object: S(t)
survt <- Surv(tstart, tstop, event)
cox1 <- coxph(survt ~ var1, control = coxph.control(timefix = FALSE))

Thank you!

**Comment by therneau** [comment]
I cannot replicate an error without any data.

**Comment by geraldinekoh** [comment]
I've managed to resolve the error.
