### ISSUE TITLE
summary.coxph fails when there are zero events

### ISSUE THREAD

**Issue by thornend** [therneau/survival#79]
Example:
```
flAllSurv <- flchain[flchain$death %in% 0, ]
coxObj1 <- coxph(Surv(flchain$futime, flchain$death) ~ flchain$sex)
summary(coxObj1)
coxObj2 <- coxph(Surv(flAllSurv$futime, flAllSurv$death) ~ flAllSurv$sex)
summary(coxObj2)
```
In 2.44-1.1, the last line gives the following error:
Error in round(cox$wald.test, 2) : 
  non-numeric argument to mathematical function
The cause is that in 2.44-1.1 coxph does not return a value for wald.test where there are no events, and round(NULL, 2) in summary.coxph then returns an error.  In 2.43 the summary.coxph returns NaN for the Wald test in this situation.   
Of course coxph makes no sense with no events, but in production code that situation sometimes occurs.

**Comment by therneau** [comment]
Now fixed.
