### ISSUE TITLE
`survfit` Kaplan-Meier probabilities clarification

### ISSUE THREAD

**Issue by symbalex** [therneau/survival#80]
I think there's an issue with estimate of the survival function using `survfit`.

I have gone back to the original paper for the KM estimator, _Nonparametric Estimation from Incomplete Observations_ 1958 (available [here](https://web.stanford.edu/~lutian/coursepdf/KMpaper.pdf)) and am using the example from Table 464 in the paper. Reproducing the methods by hand in R, and then comparing it to the responses from `survfit`, I am not getting the same answer.

![Screen Shot 2019-08-19 at 14 58 18](https://user-images.githubusercontent.com/34049418/63308299-5e0b6980-c335-11e9-9e1e-6ccedca2f8f0.png)

Above is an example - the black curve is the results from `survfit`, and the blue curve are the paper's values of the survival function estimate.

I have created a gist with an example of the above: see https://gist.github.com/symbalex/713eb9476138224254f95055403f9c8e

Is this an issue, or by design? Thanks very much.

**Comment by therneau** [comment]
Here is the example, using much simpler code.  The package agrees with their results.  I don't know what you did wrong.

# data for table 464 in Kaplan and Meier
kmdat <- data.frame(time=c(0.8, 3.1, 5.4, 9.2, 1, 2.7, 7, 12.1),
                    status=c(1,1,1,1,0,0,0,0))

# compute the KM
fit <- survfit(Surv(time, status) ~1, kmdat)

# compare to the values in their table
print(fit)
all.equal(fit$surv[fit$n.event==1], c(7/8, 7/10, 21/40, 21/80))
