### ISSUE TITLE
NA in survfit() of Multivariate Cox Regression Analysis

### ISSUE THREAD

**Issue by HeyLifeHD** [therneau/survival#88]
Dear survival authors,

First of all thanks for the great package. I am relatively new to survival analysis and was running some multivariate cox regression analysis. 
I was having some major problems when trying to visualize the estimated distribution of survival times. It resulted in NA in the median as well as the confidence intervals. 
I would be super grateful if you could help me out with the code or see if this might be a bug:

> # Create the new data to model specific effects
> str(met_clinical_sub_plot)
'data.frame':   1904 obs. of  24 variables:
 $ PATIENT_ID                   : chr  "MB-0000" "MB-0002" "MB-0005" "MB-0006" ...
 $ LYMPH_NODES_EXAMINED_POSITIVE: int  10 0 1 3 8 0 1 1 1 0 ...
 $ NPI                          : num  6.04 4.02 4.03 4.05 6.08 ...
 $ CELLULARITY                  : chr  "" "High" "High" "Moderate" ...
 $ CHEMOTHERAPY                 : chr  "NO" "NO" "YES" "YES" ...
 $ COHORT                       : int  1 1 1 1 1 1 1 1 1 1 ...
 $ ER_IHC                       : Factor w/ 2 levels "Negative","Positve": 2 2 2 2 2 2 2 2 2 1 ...
 $ HER2_SNP6                    : Factor w/ 4 levels "GAIN","LOSS",..: 3 3 3 3 3 3 2 3 1 2 ...
 $ HORMONE_THERAPY              : chr  "YES" "YES" "YES" "YES" ...
 $ INFERRED_MENOPAUSAL_STATE    : chr  "Post" "Pre" "Pre" "Pre" ...
 $ INTCLUST                     : chr  "4ER+" "4ER+" "3" "9" ...
 $ AGE_AT_DIAGNOSIS             : num  75.7 43.2 48.9 47.7 77 ...
 $ OS_MONTHS                    : num  140.5 84.6 163.7 164.9 41.4 ...
 $ OS_STATUS                    : chr  "LIVING" "LIVING" "DECEASED" "LIVING" ...
 $ CLAUDIN_SUBTYPE              : Factor w/ 7 levels "Basal","claudin-low",..: 2 4 5 5 5 5 5 2 5 3 ...
 $ THREEGENE                    : Factor w/ 5 levels "","ER-/HER2-",..: 2 3 1 1 3 3 1 1 3 3 ...
 $ VITAL_STATUS                 : chr  "Living" "Living" "Died of Disease" "Living" ...
 $ LATERALITY                   : chr  "Right" "Right" "Right" "Right" ...
 $ RADIO_THERAPY                : chr  "YES" "YES" "NO" "YES" ...
 $ HISTOLOGICAL_SUBTYPE         : chr  "Ductal/NST" "Ductal/NST" "Ductal/NST" "Mixed" ...
 $ BREAST_SURGERY               : chr  "MASTECTOMY" "BREAST CONSERVING" "MASTECTOMY" "MASTECTOMY" ...
 $ MedianSign                   : num  6.77 6.81 7 6.98 7.08 ...
 $ group                        : Factor w/ 2 levels "low","high": 1 1 NA NA NA 2 NA 2 NA 1 ...
 $ status                       : logi  FALSE FALSE TRUE FALSE TRUE TRUE ...
> res.cox3 <- coxph(Surv(OS_MONTHS, status) ~  AGE_AT_DIAGNOSIS + THREEGENE + group  , data =  met_clinical_sub_plot)
> res.cox3 
Call:
coxph(formula = Surv(OS_MONTHS, status) ~ AGE_AT_DIAGNOSIS + 
    THREEGENE + group, data = met_clinical_sub_plot)

                                    coef exp(coef)  se(coef)      z        p
AGE_AT_DIAGNOSIS               -0.007145  0.992880  0.005458 -1.309   0.1905
THREEGENEER-/HER2-             -0.459369  0.631682  0.227789 -2.017   0.0437
THREEGENEER+/HER2- High Prolif  0.135917  1.145587  0.232319  0.585   0.5585
THREEGENEER+/HER2- Low Prolif  -0.560855  0.570721  0.323805 -1.732   0.0833
THREEGENEHER2+                 -0.127614  0.880193  0.260228 -0.490   0.6239
grouphigh                       1.047732  2.851177  0.241429  4.340 1.43e-05

Likelihood ratio test=69.69  on 6 df, p=4.725e-13
n= 653, number of events= 203 
   (1251 observations deleted due to missingness)
> 
> model_3Int_1df <- with(met_clinical_sub_plot,
+                data.frame(
+                           AGE_AT_DIAGNOSIS = rep(mean(AGE_AT_DIAGNOSIS, na.rm = TRUE), 2),
+                           THREEGENE=c(levels(met_clinical_sub_plot$THREEGENE)[1],levels(met_clinical_sub_plot$THREEGENE)[1]),
+                           group=c(levels(met_clinical_sub_plot$group)[1], levels(met_clinical_sub_plot$group)[2])
+                ))
> str(model_3Int_1df)
'data.frame':   2 obs. of  3 variables:
 $ AGE_AT_DIAGNOSIS: num  61.1 61.1
 $ THREEGENE       : Factor w/ 1 level "": 1 1
 $ group           : Factor w/ 2 levels "high","low": 2 1
> levels(model_3Int_1df$THREEGENE)<- levels(met_clinical_sub_plot$THREEGENE)
> levels(model_3Int_1df$group)<- levels(met_clinical_sub_plot$group)
> str(model_3Int_1df)
'data.frame':   2 obs. of  3 variables:
 $ AGE_AT_DIAGNOSIS: num  61.1 61.1
 $ THREEGENE       : Factor w/ 5 levels "","ER-/HER2-",..: 1 1
 $ group           : Factor w/ 2 levels "low","high": 2 1
> 
> fit <- survfit(res.cox3, newdata = model_3Int_1df)
> fit
Call: survfit(formula = res.cox3, newdata = model_3Int_1df)

    n events median 0.95LCL 0.95UCL
1 653    203    134    68.2      NA
2 653    203     NA      NA      NA

Thanks you very much in advance.

Cheers,

Joschka

**Comment by anoopshah** [comment]
Dear survival package authors,

I am not sure if this is the same bug but I have also encountered NA values in survfit estimates using the survival 3.1-7 package, but not in survival 2.44-1.1. I attach the dataset and output generated by running the text script using two versions of the package.

Thank you for looking into this.
Kind regards,

Anoop

----

## Script:
```
# Test script for survival package

library(survival)
version <- sessionInfo()$otherPkgs$survival$Version
sink(paste0('survtest', version, '.log'), split = TRUE)

cat('\nRunning survival version', version, '.\n')

cat('\nLoading test data.\n')
# The test data contains:
#     event (0 or 1)
#     time
#     cumhaz = Nelson-Aalen estimator of baseline
#              hazard at the time, calculated as
#              below, using survival 3.1-7
data <- read.table('survivaldata.txt', header = TRUE)
print(summary(data))

cat('\nThe dataset has', nrow(data), 'rows.\n')

cat('\nNote row with missing cumulative hazard.\n')
print(data[is.na(data$cumhaz),])

cat('\nGenerating cumulative hazard.\n')
hazard <- with(data,
	basehaz(coxph(Surv(time, event) ~ 1)))
cat('\nThe hazard has', nrow(hazard), 'rows.\n')
print(summary(hazard))

cat('\nOrdering by original time.\n')
idx <- match(data$time, hazard$time)
cumhaz <- hazard[idx, 'hazard']
summary(cumhaz)

cat('\nChecking cumhaz is same as reference.\n')
print(summary(data$cumhaz / cumhaz))

cat('\nNew cumhaz where reference is blank.\n')
print(cumhaz[is.na(data$cumhaz)])

cat('\nEnd of text script.\n')
sink()
```

## Session info:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
```

## Output using survival 2.44-1.1
```
Running survival version 2.44-1.1 .

Loading test data.
     event            time              cumhaz      
 Min.   :0.000   Min.   :0.000341   Min.   :0.0020  
 1st Qu.:0.000   1st Qu.:0.089735   1st Qu.:0.1334  
 Median :0.000   Median :0.194417   Median :0.2651  
 Mean   :0.284   Mean   :0.235981   Mean   :0.2840  
 3rd Qu.:1.000   3rd Qu.:0.379007   3rd Qu.:0.4390  
 Max.   :1.000   Max.   :0.642358   Max.   :0.5236  
                                    NA's   :1       

The dataset has 500 rows.

Note row with missing cumulative hazard.
    event      time cumhaz
473     0 0.2150044     NA

Generating cumulative hazard.

The hazard has 500 rows.
     hazard            time         
 Min.   :0.0020   Min.   :0.000341  
 1st Qu.:0.1334   1st Qu.:0.089735  
 Median :0.2651   Median :0.194417  
 Mean   :0.2840   Mean   :0.235981  
 3rd Qu.:0.4390   3rd Qu.:0.379007  
 Max.   :0.5236   Max.   :0.642358  

Ordering by original time.

Checking cumhaz is same as reference.
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      1       1       1       1       1       1       1 

New cumhaz where reference is blank.
[1] 0.3066917

End of text script.
```

## Output using survival 3.1-7
```
Running survival version 3.1-7 .

Loading test data.
     event            time              cumhaz      
 Min.   :0.000   Min.   :0.000341   Min.   :0.0020  
 1st Qu.:0.000   1st Qu.:0.089735   1st Qu.:0.1334  
 Median :0.000   Median :0.194417   Median :0.2651  
 Mean   :0.284   Mean   :0.235981   Mean   :0.2840  
 3rd Qu.:1.000   3rd Qu.:0.379007   3rd Qu.:0.4390  
 Max.   :1.000   Max.   :0.642358   Max.   :0.5236  
                                    NA's   :1       

The dataset has 500 rows.

Note row with missing cumulative hazard.
    event      time cumhaz
473     0 0.2150044     NA

Generating cumulative hazard.

The hazard has 499 rows.
     hazard            time         
 Min.   :0.0020   Min.   :0.000341  
 1st Qu.:0.1334   1st Qu.:0.089684  
 Median :0.2651   Median :0.193212  
 Mean   :0.2840   Mean   :0.236023  
 3rd Qu.:0.4390   3rd Qu.:0.379179  
 Max.   :0.5236   Max.   :0.642358  

Ordering by original time.

Checking cumhaz is same as reference.
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      1       1       1       1       1       1       1 

New cumhaz where reference is blank.
[1] NA

End of text script.
```
## Dataset
[survivaldata.txt](https://github.com/therneau/survival/files/3869299/survivaldata.txt)

**Comment by therneau** [comment]
1. To HeyLife.   If a survival curve does not fall below .5 then the median survival is undefined.  This is common and expected.   There is no bug.

2. To anoopshah.   You cannot expect the get a perfect match with arbitrary floating point values.  See the R FAQ 7.31, and also the vignette on tied times in this package.
