### ISSUE TITLE
degrees of freedom in survdiff() function

### ISSUE THREAD

**Issue by yikeshu0611** [therneau/survival#89]
Dear professor Terry M Therneau
   I do analysis by using survival package as follows:
   `library(survival)`
   `logrank=survdiff(Surv(qsec,vs)~mpg,data=mtcars)`
   `logrank`

> Call: 
> survdiff(formula` = Surv(qsec, vs) ~ mpg, data = mtcars)
>                     N Observed Expected (O-E)^2/E (O-E)^2/V
> mpg=10.4 2    0   0.0833   0.08333   0.09091
> mpg=13.3 1        0   0.0000       NaN       NaN
> mpg=14.3 1        0   0.0000       NaN       NaN
> mpg=14.7 1        0   0.0417   0.04167   0.04348
> mpg=15   1        0   0.0000       NaN       NaN
> mpg=15.2 2        0   0.0833   0.08333   0.09091
> mpg=15.5 1        0   0.0000       NaN       NaN
> mpg=15.8 1        0   0.0000       NaN       NaN
> mpg=16.4 1        0   0.0417   0.04167   0.04348
> mpg=17.3 1        0   0.0417   0.04167   0.04348
> mpg=17.8 1        1   0.6151   0.24093   0.27812
> mpg=18.1 1        1   2.2079   0.66083   0.90407
> mpg=18.7 1        0   0.0417   0.04167   0.04348
> mpg=19.2 2        1   0.1603   4.40026   4.78422
> mpg=19.7 1        0   0.0000       NaN       NaN
> mpg=21   2        0   0.0417   0.04167   0.04348
> mpg=21.4 2        2   1.0507   0.85757   1.02454
> mpg=21.5 1        1   1.7079   0.29342   0.36744
> mpg=22.8 2        2   3.6007   0.71163   1.34289
> mpg=24.4 1        1   1.3746   0.10207   0.12290
> mpg=26   1        0   0.0000       NaN       NaN
> mpg=27.3 1        1   0.6151   0.24093   0.27812
> mpg=30.4 2        2   0.2436  12.66464  13.78553
> mpg=32.4 1        1   0.9246   0.00615   0.00716
> mpg=33.9 1        1   1.1246   0.01380   0.01627
>  **Chisq= 25.5  on 17 degrees of freedom, p= 0.08**

We see the p value is **0.08**, degree of freedom is **17**. Because the result has 7 NaN, so the degree is 25 -1 - 7, equaling to 17. 
However! In some other methords for calculating the p value of log-rank test based on survival package, they take different degrees.
**Methord 1 :**
`1 - pchisq(logrank$chisq, length(logrank$n) - 1 )`
This methord is used widely. It takes _**length(logrank$n) - 1**_ as the degree, which is **24 (25-1)**. The p value is **0.38**.
**Methord 2 :**
Package `emil` provides `pvalue` function to extract the p value from survdiff results.  [https://github.com/Molmed/emil](url)
`emil::pvalue(logrank)`
This function takes the same methord with Methord 1. So p value is still **0.38**
**Methord 3 :**
Package `survminer` also provides `ggsurvplot` function to display p value in survival plot.
`library(survminer)`
`fit<- survfit(Surv(qsec,vs)~mpg,data=mtcars)`
`ggsurvplot(fit,data=mtcars,  pval =  TRUE)`
The p value is still **0.38**.

I think these 3 methords take the same degree, 24, to calculate p value by chi-square test. However, the degree in `survival` package is 17, which omit 7 NaNs. 
So my question is: which degree is right?
Best Wishes
Jing Zhang

**Comment by therneau** [comment]
1. Survdiff is designed for categorical predictors, not for continuous ones.  There are 30 unique values for 32 cars.  Do you think that testing groups of size n=1 is valid?
2. The example is very odd: treat a V8 engine as "censored" and an inline engine as "not"?
3. If  you have an actual question about real data, I will try to answer it.

**Comment by yikeshu0611** [comment]
Thanks
