### ISSUE TITLE
not finite in coxph.wtest

### ISSUE THREAD

**Issue by HeidiSeibold** [therneau/survival#91]
I wonder why the following lines are printed instead of returning a warning/error.

For me this lead to some confusion.

https://github.com/therneau/survival/blob/67f4a4036b03d493de6384dedf9967c6ab079644/R/coxph.wtest.R#L30-L34

Any thoughts? Thank you :sunflower:

**Comment by dezhanglee** [comment]
I agree. shouldn't the test be stopped?

**Comment by therneau** [comment]
It looks like a leftover debugging line.  Hmm....

**Comment by therneau** [comment]
Now removed
