### ISSUE TITLE
pspline.predict not working properly

### ISSUE THREAD

**Issue by yuqinouou** [therneau/survival#98]
Hi, maybe not a lot of people use pspline.predict(), but there seem to be some obvious issues in it.
https://github.com/therneau/survival/blob/a99481da024bf1cf2d833414caafc65b2327426c/R/pspline.R#L205-L206
Something like below works for my use case, but I'm not 100% sure it is good enough.
```
   a <- c(list(x=newx, penalty=FALSE), 
           attributes(object)[c("nterm", "intercept", "Boundary.knots", "combine")])
```

**Comment by therneau** [comment]
I rarely use the nterm argument, so had not picked up this error.   A half dozen line earlier in the same code, the makepredictcall method did it correctly.
Thanks

**Comment by yuqinouou** [comment]
https://github.com/therneau/survival/blob/a25dbbc6dc5c02d59068f3aad6e336eef1e09d56/R/pspline.R#L205-L206
Sorry for reopening this, but another error is the missing separation between intercept and Boundary.knots
`... "intercept", "Boundary.knots" ...`
Thanks
