### ISSUE TITLE
plot.cox.zph() with factors with more than 2 levels

### ISSUE THREAD

**Issue by danielegiardiello** [therneau/survival#99]
Dear all,

I typically use the function cox.zph() and the corresponding plot to check the proportional hazard assumption of a Cox model.

I have recently noted that now when a factor X1 with K levels is included in this model, only one "global" plot of X1 is generated instead of K-1 plots (one for every K-1 betas). How this plot is generated? Might it be a bug or my ignorance?

If I remember correctly in the past K-1 plots were generated to check the PH assumption for every K-1 coefficients of X1. 

Now to check the PH assumption for every coefficients, K-1 dummy variables should be created.

Really thanks and apologize maybe it is a naive question.
Best,
Daniele

**Comment by Feakster** [comment]
Each level of the factor variable (excluding the reference level) will be internally coded as a separate variable. Check the help file for `plot.cox.zph`. It has a `var` parameter that you can use the specify the variable you want to assess. I don't know how the factor variable levels would be internally coded by the `cox.zph()` function (probably just a concatenation of the `variable` name and `level` name), but `var` can also be a number, aligning to the `indices` of the model matrix that would be used by the initial `coxph()` function.

**Comment by danielegiardiello** [comment]
Using the package version 3.1.8, , the solution you have proposed unfortunately does not work anymore. In previous version, yes (e.g. before I used 2.44.1.1)
Use the package version 3.1.8 and run the following code to realize it.

library(pec)
library(survival)

set.seed(123456)
db<-SimSurv(1000)
db$X3<-runif(1000)
db$X4<-NA
db$X4[db$X3<0.3]<-1
db$X4[db$X3>=0.3 & db$X3<0.6]<-2
db$X4[db$X3>=0.6]<-3
db$X4<-factor(db$X4,1:3,labels=c('Low','Medium','High'))
head(db)

cox<-coxph(Surv(time,status)~X4,data=db)
cox

cox.zph(cox)
# win.graph() # to report multiple windows with figures in WINDOW
plot(cox.zph(cox))  # QUESTION: which beta for X4 is reported?

# Creating the dummy variables
db$X4_Low<-ifelse(db$X4=='Low',1,0)
db$X4_Medium<-ifelse(db$X4=='Medium',1,0)
db$X4_High<-ifelse(db$X4=='High',1,0)

cox_dummy<-coxph(Surv(time,status)~X4_Medium+X4_High,data=db)
cox_dummy # same results of cox, of course.
# win.graph() # to report multiple windows with figures in WINDOW
plot(cox.zph(cox_dummy))

**Comment by Feakster** [comment]
Looks like a bug. Just tested it in the latest version from GitHub (3.1-10), and it's still there. The plot you get from the first example differs from the plots you get from using `plot(cox.zph(cox_dummy), var = "Medium")` and `plot(cox.zph(cox_dummy), var = "High")` in the second.

**Comment by danielegiardiello** [comment]
Yes, it may be a bug to my modest experience. I do not know in the first model how the residuals are computed. I can understand the global chi-squared test for PH assumption (with K-1 df) but for the figure provided I have no explanations unless ignorance about my knowledge.

**Comment by therneau** [comment]
Perhaps you might start by reading the help page?  

The cox.zph command now has a "terms" argument which defaults to TRUE.   It is a long overdue addition.   When linear models contain a factor variable one can look at test/p-values for each individual coefficient, or a global test for the term as a whole (e.g using anova()).   Theory tells us that a global test is the preferred route.  Not everyone agrees of course, and we could certainly rehash 50 years of linear model arguments, but for cox.zph instead.  If you want the old behavior call the function with terms=FALSE.  

The lm version of the speculation about a "bug" above is essentially asking "why doesn't the anova p-value match any of the individual coefficient tests".   The answer is that it shouldn't match.  There is no bug.
More detail about the computations is found in the vignette, which also updated.   The test is a multi df score test, and the plot is an assessment of PH for each term's contribution to the linear predictor, in the flavor of predict(type='terms').

(I don't often log into github.  You will get faster resonse with email.)

**Comment by danielegiardiello** [comment]
Thanks. I focused on reading the help for the plot forgetting to read properly the help of cox.zph(). Really thanks.

**Comment by Feakster** [comment]
Same. Didn't think to look in the `cox.zph()` helpfile. Apologies.
